### ISSUE TITLE
Connection reset by peer (10054)

### ISSUE THREAD

**Issue by DrElectrons** [TigerVNC/tigervnc#1041]
** Bug **
TigerVNC Viewer
read: Connection reset by peer (10054)

randomly occurs approximately once a day.
My colleagues using other VNC tools do not have this issue.
Could this be a timeout being too short? Can a timeout looking for periodic communication be increased to stop this error.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/66701453/84203030-91062180-aa5d-11ea-84b6-a81893981fc6.png)

**Client (please complete the following information):**
 - OS: Latest Windows 10
 - VNC client: TigerVNC
 - VNC client version: [e.g. 1.8.0]
 - Client downloaded from: [e.g. my Linux distribution]

**Server (please complete the following information):**
 - OS: [e.g. Windows 8.1]
 - VNC server: [e.g. TigerVNC, or UltraVNC]
![image](https://user-images.githubusercontent.com/66701453/84203066-a8450f00-aa5d-11ea-93ea-2f9fbec8cd6f.png)
- VNC server on Linux system
![image](https://user-images.githubusercontent.com/66701453/84203466-551f8c00-aa5e-11ea-878b-939caaa86325.png)

**Additional context**
Logfile
[radon.atomera.local%3A6.log](https://github.com/TigerVNC/tigervnc/files/4755008/radon.atomera.local.3A6.log)

**Comment by CendioOssman** [comment]
That particular error is generated when the server crashes, or when something on the network kills the connection. Since the server is still running it must be something external that killed the connection.

Unfortunately that means we can't really provide much assistance. Please check your firewalls (or antivirus) or other network devices and try to figure out which device is causing this. It might be some security setting, or that it aggressively drops connection it thinks are idle.
