### ISSUE TITLE
vncserver symlink lost upgrading from 1.10.1 1.11.0

### ISSUE THREAD

**Issue by gsaviane** [TigerVNC/tigervnc#1105]
vncserver symlink no longer available in CLI.

1. Install new Debian package with sudo dpkg -i tigervncserver_1.11.0-1ubuntu1_amd64.deb over an existing 1.10.1 version
2. Try to run vncserver via CLI
3. Returned error: vncserver: command not found

Expected behavior:
The process could start and run Xvnc settings from ~/.vnc directory

Server (please complete the following information):
 - OS: Ubuntu 16.04
 - VNC server: TigerVNC
 - VNC server version: 1.11.0
 - Server downloaded from: this website
 - Server was started using: vncserver

**Comment by fcying** [comment]
got the same problem
I saw update log have `vncserver has gotten a major redesign to be compatible with modern distributions`. 
I don't know if it is related about this.

**Comment by craigefrein** [comment]
Also happening on fedora 32 after upgrading from dnf.

**Comment by featherly** [comment]
ditto on Fedora 32 upgrade to version 1.11.0-1

**Comment by accetto** [comment]
I can also confitm the problem. I had to add the following link to my Dockerfiles:

`ln -s /usr/libexec/vncserver /usr/bin/vncserver`

**Comment by CendioOssman** [comment]
That is correct. Starting things by running `vncserver` directly is no longer supported as it is simply too unreliable for us to support. If you want something more custom than a standard desktop session then I'm afraid you'll have to put together your own startup script with what you need.

**Comment by craigefrein** [comment]
Hello Pierre,

Why does having a command line version of vncserver cause issues for you?
What other options do users have to execute vncserver as simply as it was
before in Fedora?

This was my command line: vncserver -geometry 1280x800

That's all I want to continue doing. Is that still possible with the
upgraded version?

Thanks,
Craig




Website: http://cnstechgroup.com/

Contact: (619) 630-8758
Mobile: (+33) 6 31 74 17 37

**Comment by CendioOssman** [comment]
>  Why does having a command line version of vncserver cause issues for you?

Because for most users it started a desktop that didn't work in various ways. And we couldn't really help users, which wasn't nice for anyone involved.

Keeping both wasn't really an appealing idea either as there was a lot of risk for confusion, and we don't have a reliable scenario for `vncserver`. Right now it's pretty much random when it works and when it doesn't. We can't really support users when they get stuck if the system wasn't reliable to begin with.

So the situation now is that we have the new `vncserver` service, which should reliably start desktop sessions. And we still have and support `Xvnc` as a X11 server for people who do everything from scratch. But if you want to start something other than a desktop session then the requirements are pretty much unknown, so we cannot include anything for that.

> What other options do users have to execute vncserver as simply as it was before in Fedora? This was my command line: vncserver -geometry 1280x800 That's all I want to continue doing. Is that still possible with the upgraded version?

No, it is not.

If your xstartup started a desktop session then you should switch over to the new service. If you did something more custom than you can probably use that as a base to construct your own startup. You're mostly just missing calling `xauth` and `Xvnc`.

**Comment by craigefrein** [comment]
Hello Pierre,

Perhaps to you all of this makes perfect sense, but in all the years I've
been using tigervnc-server, there were never any stability issues. In fact
the only stability issue I ran into was when you removed vncserver and I
found out the hard way like the other people that replied to this issue.

That said, and moving forward, I have been unable so far to get
tigervnc-server to work using the new version in Fedora 32. Would you be
able to provide step by step instructions for installing and running the
new tigervnc-server under Fedora 32?

Thank you,
Craig




Website: http://cnstechgroup.com/

Contact: (619) 630-8758
Mobile: (+33) 6 31 74 17 37

**Comment by CendioOssman** [comment]
>  That said, and moving forward, I have been unable so far to get tigervnc-server to work using the new version in Fedora 32. Would you be able to provide step by step instructions for installing and running the new tigervnc-server under Fedora 32?

The instructions in the service file should be enough to get something started:

https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/vncserver%40.service.in

If that doesn't work then please file a new issue and provide as much information as you can about what you've tried. Then we can see where things might have gone wrong.

**Comment by craigefrein** [comment]
Hello again,

After following all the steps in the readme you sent, here is the error
message after attempting to start the vnc service.



Sep 28 10:14:33 themachine systemd[1]: vncserver@1.service: Failed with
result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- The unit vncserver@1.service has entered the 'failed' state with result
'exit-code'.
Sep 28 10:14:33 themachine systemd[1]: Failed to start Remote desktop
service (VNC).
-- Subject: A start job for unit vncserver@1.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- A start job for unit vncserver@1.service has finished with a failure.
-- 
-- The job identifier is 2450 and the job result is failed.
Sep 28 10:14:33 themachine audit[1]: SERVICE_START pid=1 uid=0
auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0
msg='unit=vncserver@1 comm="systemd" exe="/usr/lib/systemd/systemd" hostnam>
lines 2887-2941/2941 (END)




Website: http://cnstechgroup.com/

Contact: (619) 630-8758
Mobile: (+33) 6 31 74 17 37

**Comment by craigefrein** [comment]
Hello Pierre,

So I am able to start a vncserver with this command from root: *vncsession
cefrein :1* but not using the systemctl start command which
systematically fails.

I did add an entry :1=cefrein to */etc/tigervnc/vncserver.users*

vncpassword is set of course, no useful errors from /var/log/messages

Thanks,
Craig




Website: http://cnstechgroup.com/

Contact: (619) 630-8758
Mobile: (+33) 6 31 74 17 37

**Comment by abryant-hv** [comment]
Those of us who have worked this way for years would really appreciate some sort of migration documentation. Maybe it exists, but I can't find it.

**Comment by abryant-hv** [comment]
Specifically, how do we now: 
- run a vncserver that is not associated with the desktop (personally, I can't because my desktop is huge, for multiple local displays, and I don't have that when working remotely... I need to be able to create a second session unrelated to the first) vncsession seems to maybe be able to do this, but it also wants to run as root, which is sketchy. 
- *STOP* that session? I see nothing in current docs about stopping a session. Logging out does nothing and leaves the session running.

**Comment by CendioOssman** [comment]
> Those of us who have worked this way for years would really appreciate some sort of migration documentation. Maybe it exists, but I can't find it.

It does not, unfortunately. Time is unfortunately a very limited resource for this project so this wasn't possible (yet at least).

>     * run a vncserver that is not associated with the desktop (personally, I can't because my desktop is huge, for multiple local displays, and I don't have that when working remotely... I need to be able to create a second session unrelated to the first) vncsession seems to maybe be able to do this, but it also wants to run as root, which is sketchy.

It won't run as root, but it needs to start out as root as creating a new user session is a privileged operation. After that everything will run as the user specified.

> STOP that session? I see nothing in current docs about stopping a session. Logging out does nothing and leaves the session running.

It should terminate if you log out so if it doesn't then there is something wrong. Please file an issue about that.

Forcefully stopping is done via systemd, since that is what starts the sessions.
