### ISSUE TITLE
happy living with vncserver seems gone

### ISSUE THREAD

**Issue by torbjorn** [TigerVNC/tigervnc#1116]
So my situation is like this:

1) I use vncserver when I do  end-to-end testing fo web applications. Instead of having a browser window jumping around on my desktop and doing stuff, ocationally stealing focus, I run this in vnc using DISPLAY :1. It works great. I can keep working on stuff while test suite does it job in the background. Occationally I look at it to see everything is ok. Perfect solution for me, and a bunch of other people I imagine.

2) I sometime ssh in to my workstation to do data analysis. This involves frequent plotting of graphs. Instead of doing a sluggish X11 forward over ssh for large complex graphs, and have these Xclients darg down my Xserver experience, I change DISPLAY to :2 and run a vncserver there. I connect to this with a local viewer and enjoy stressless data plotting all night long.

All these seem perfectly valid use cases. And these were just the ones I chipped off at the top of my head.

So now running vncserver :1 etc. is gone, because of demands of modern desktop environments?

This makes absolutely no sense. I have to call the sys admin, ask him to read up on all this shiny new stuff, to create systemd service files for every single vncserver display I want to open up? This is, excuse me, total ********.

I ran twm in vnc. It sure never complained? Why did this new change have to interfere with the way I lived in happy harmony with twm?

Can we please have vncserver back?

Put in a check or something if you seem to be running a demanding DE (gnome,kde,cinnamon,...), telling the user only older more simplistic DE's are supported, and problem solved, this great flexibility to graphics-over-network (as is vnc) is maintained.

**Comment by CendioOssman** [comment]
It sounds like your use case just needs `Xvnc`? Have you tried starting that directly instead of using the vncserver script?

**Comment by torbjorn** [comment]
I don't know.

Running `Xvnc :1` spews warnings, but it starts, but it does not accept my vnc password.

Looking at the vncserver script from a centos machine that still has the old version, it's around 900 lines long, most if which seems to be stuff that does something useful.

Couldn't the vncserver script just be left as it is somewhere not in path so users who know what it is can still call it directly? It's been around for 20 years or more, a soft deprecation seems apropriate, not a hard removal.

**Comment by MarkMielke** [comment]
Adding a voice here... I have 1k+ users at my company that this will directly affect. We do not have the problems mentioned as the reason for why vncserver is deprecated in favor of systemd startup. In fact, it's probably the opposite - the change will directly break all the carefully defined $HOME/.vnc/xstartup files that people have built over the years.

I've been too busy to deal with this, and have instead been using a heavily patch 1.10, without any of the systemd changes. Once I do have time to look at this, and if the changes do not work for us - I will be forced to create a branch for our company that restores much or all of vncserver to working order. In such a case, I suppose it will depend upon whether the TigerVNC maintainers accept a patch to restore some functions, or whether I have to maintain a fork. If a fork does have to be maintained, I will probably publish it. I don't want to compete here - but this is a question of divergence in expectations, and my 1k+ users can't all of a sudden change their own 20+ years of it working a certain way, just because the upstream has abandoned this use case.

I will mention it's not just the automatic startup of VNC within a session that breaks here - but we also use multiple VNC sessions per machine including ad-hoc setups, such as multi-user machines (sometimes 20+ users sharing a machine!), and also fully automatic startups, like when a particular simulation starts we want to launch a series of windows within a VNC session and allow the user to connect in to see what the windows are all showing. Even if these could be better written against Xvnc instead of "vncserver", the effort to adapt them is too much. It will be much easier for me to restore the functionality into vncserver.

**Comment by Asheswright** [comment]
This change has caught me completely unaware. vncserver was the main way I used vnc, and it is just gone with almost no warning.

I would appreciate the old vncserver functionality in a script.
Or some documentation on how to achieve the old way of running vncserver in the new environment.

For me, this change is a major break in functionality.

**Comment by smithcom1** [comment]
I am running: tigervnc-1.11.0-1.fc32.x86_64

Since systemd support is gone :(

I have two Fedora 32 Machines.

I did the following (Fedora 32 Machine1):

added username to: 
/etc/tigervnc/vncserver.users
:1=<LOCAL USERNAME>

Ran as root:
/usr/libexec/vncsession-start :1

On remote workstation (Fedora 32 Machine2)
VNC Viewer:  <IP Address>:1

Accepted vnc password first time (vncpasswd works)

OS Login screen came up 
I had to type in my password 5 to 6 time before I logged into a gnome desktop (I am using Mate) 
This there a issue reading .vnc/xstartup or pam issue ?
Are there better docs out there on "improvements"?

Thanks.

**Comment by CendioOssman** [comment]
> 
> Running `Xvnc :1` spews warnings, but it starts, but it does not accept my vnc password.
> 

Ah, I though it defaulted to the "normal" password file but apparently there is no default. So you need to specify `-PasswordFile ~/.vnc/passwd` as well.

> Couldn't the vncserver script just be left as it is somewhere not in path so users who know what it is can still call it directly? It's been around for 20 years or more, a soft deprecation seems apropriate, not a hard removal.

We don't want to include stuff we cannot support, so that's why it was completely removed. You are free to keep a copy of it and use though. It should still work the same even with an updated Xvnc.

**Comment by MarkMielke** [comment]
Perhaps a compromise would be to publish only the updated "vncserver" script in a separate repository, for those that need it. I do think the idea of "support" in a community is a bit subjective. I mean that the community exists to provide the support, and people such as myself would provide the support - since we use it, and this is not really any different than Cendio supporting the parts they choose to. I think the problem only comes up when users claim something is broken and demand support, but aren't willing to roll up their own sleaves to contribute. In this case, it is a community problem. Not an individual or single company problem.

**Comment by karolyi** [comment]
I'll add another problem area: FreeBSD and its relatives.

I've been using the vncserver script the same way others described here, without any hassle. The script disappeared in 1.11, and mind you guys, BSDs have none of the systemd stuff, so I ended up with a lot of errors, by installing the newest package. I even added a bugreport in FreeBSD about this: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=250143

Can we have the non-systemd functionality with running the vncserver script as an use, so I don't have to run it as root, just to get some small stuff done?

**Comment by CendioOssman** [comment]
> I think the problem only comes up when users claim something is broken and demand support, but aren't willing to roll up their own sleeves to contribute.

Which is unfortunately far too common and we were seeing a issues reported here, and on the mailing lists. So we had to make a clear stand here.

> Perhaps a compromise would be to publish only the updated "vncserver" script in a separate repository, for those that need it.

Sure. But I don't want to include it in our packing or we'll get the issue with people complaining if it doesn't work. So feel free to put up a repo with a more community maintained script. We can link it from our wiki here for people that can't use our recommended way.

**Comment by CendioOssman** [comment]
> I'll add another problem area: FreeBSD and its relatives.

I'm afraid we don't have anyone with the expertise of how things should work on the BSDs, so right now I'm afraid we cannot support a full session startup for you guys. :/

**Comment by CendioOssman** [comment]
Hopefully @torbjorn has gotten what he needs so I'm going to go ahead and close this issue. For more discussion about the new session startup and removal of the old script, please use the mailing lists as the issue tracker is better suited for specific issues.

**Comment by karolyi** [comment]
does anyone have a link to the old vncserver script so at least I can test if it still works?

sad to see this issue being closed as is.

**Comment by CendioOssman** [comment]
You can always grab it out of an old release. Or via the repo:

https://raw.githubusercontent.com/TigerVNC/tigervnc/v1.10.1/unix/vncserver

**Comment by karolyi** [comment]
Thanks.

With this, and a little tweaking, I was able to get Xvnc working in my FreeBSD jail, as an user. Updated the above linked ticket, hopefully it'll land in the FreeBSD package soon.

**Comment by torbjorn** [comment]
Right, I obbviously didn't get what I need, but I acknowledge the train has left the station on this one.

The _proper_ way to handle this, would have been to leave a _deprecation warning_ some time ahead. This means the community can step in in good time to take over maintenance of this functionality, if necessary. The response to this thread should be an obvious testament to its neccessity.

Sorry for the pedantic tone, but it is well deserved. Become better persons and do it right next time.
