### ISSUE TITLE
Xvnc stderr logging broken in inetd mode

### ISSUE THREAD

**Issue by CendioOssman** [TigerVNC/tigervnc#1130]
**Describe the bug**
If Xvnc is started with `-inetd` then the logging doesn't work.

**To Reproduce**
1. Set up TigerVNC in accorande with:
    https://wiki.archlinux.org/index.php/XDMCP
    https://wiki.archlinux.org/index.php/TigerVNC#On_demand_multi-user_mode
2. Connect

**Expected behavior**
Log messages in the journal.

**Client (please complete the following information):**
Any

**Server (please complete the following information):**
 - OS: Linux
 - VNC server: TigerVNC
 - VNC server version: `master`
 - Server was started using: systemd (see above)

**Additional context**
Explicitly specifying `-Log *:stderr:30` (the default) seems to fix it though.

**Comment by CendioOssman** [comment]
This seems to be an explicit behaviour:

https://github.com/TigerVNC/tigervnc/blob/32222b3bf61974f1e26ef857cd44fe710a229f86/unix/xserver/hw/vnc/xvnc.c#L556-L568

It was recently changed in commit 712cf8673d6e57442f41636e44020f5e1839c7f8.

The description doesn't seem to be accurate though as it seems to be fine to log in inetd mode if you explicitly configure logging. Some investigation is needed.

**Comment by CendioOssman** [comment]
This issue was originally noticed on #1023.

**Comment by grulja** [comment]
@jwrdegoede do you have an idea?

**Comment by jwrdegoede** [comment]
This is also been discussed here:
https://bugzilla.redhat.com/show_bug.cgi?id=1841537
(which should be a public bug AFAICT) 

Let me just copy and paste what I said there:

(In reply to Pierre Ossman from comment #11)
> I think it was broken before Hans' change as well since there was a close(2)
> there.

Right, mixing inetd usage and stderr for log output is not supported because some inetd versions will send not only anything written to stdout to the (tcp/ip) client but also anything written to stderr, see e.g.:
https://developer.ibm.com/technologies/linux/articles/au-spunix-inetd/

That is why the close(2) call was originally there; and my patch which you reference keeps the behavior of closing stderr. On top of that it now also opens /dev/null when closing stderr, since other code treats fd 2 (aka stderr) special and thus we don't want another subsequent open to return fd number 2, so we clobber that fd number now by opening /dev/null and tying it to fd 2 (which has the result of closing the resource that fd 2 was original referring to).

So since the systemd.service file is using the old inetd code paths in Xvnc and since those code paths are expected to not have a working stderr, everything seems to work as intended.

So short of adding support for systemd-style socket activation (where the stdin, stdout and stderr streams are not used for the socket) to Xvnc and using that instead of the classic inetd style socket-activation, there is nothing we can do here.

So it seems that the workaround is actually a pretty good solution here and we should just stick with it.

For more info on systemd-style socket activation see:
http://0pointer.net/blog/projects/socket-activation.html

**Comment by CendioOssman** [comment]
I guess there is nothing to do here then and everything works as it should. If someone implements systemd style socket activation then we could get some more magic, but that's for the future.

**Comment by iva2k** [comment]
Though this issue is closed, it's worth noting that it's possible to make a wrapper script for systemd style socket activation that will redirect stderror to journal. With the below approach, it would be great to have option to enable stderr, as VNC servers are so hard to troubleshoot.

/usr/bin/xvnc-inetd.sh
```bash
#!/bin/bash
# Loader for Xvnc Per-Connection Daemon
#Requires=xvnc@.service
#Requires=xvnc.socket
instance=$1
ExecStart="/usr/bin/Xtigervnc :${N} -inetd -query localhost -once -noreset -geometry 1920x1200 -depth 24 -rfbauth $HOME/.vnc/passwd"

# Redirect stderr to systemd log (journal)
exec 2> >(systemd-cat -t "xvnc-inetd.sh" -p info)

# Echo to stderr (will now show up in systemd jourlnal)
echo "$0 $@" >&2
echo "  + USER=$USER, instance=$instance" >&2
echo "  + ExecStart           = $ExecStart" >&2

#sleep 0.5
exec $ExecStart
```

/etc/systemd/system/xvnc.socket
```bash
[Unit]
Description=TigerVnc Server
[Socket]
ListenStream=5900
Accept=yes
[Install]
WantedBy=sockets.target
```

/etc/systemd/system/xvnc@.service
```bash
[Unit]
Description=Xvnc Per-Connection Daemon
[Service]
ExecStart=/usr/bin/xvnc-inetd.sh %i
StandardInput=socket
StandardError=journal
User=root
```
