### ISSUE TITLE
vncserver script for non-root users

### ISSUE THREAD

**Issue by rtheys** [TigerVNC/tigervnc#1162]
Hi,

It seems the new way to have VNC sessions is to no longer have a vncserver script, but to use the systemd unit? This requires adding users to a static file on the system and that the users either have their vnc service pre-enabled, or have sudo access to start it.

This doesn't scale for systems where 100's of students have access to. Using the vncserver script, each student could start a session as needed and use SSH tunneling for a secure transport to their vnc session.

What is the recommended setup for VNC in this scenario? 

Students are not given sudo access to workstatons, and listing them in a config file is not doable. Also, the number of vnc sessions one can create (99) is way less than the potential number of users.

Regards,
Rik

**Comment by plembo** [comment]
Traditionally, the vncserver perl script did the heavy lifting for nonprivileged users. As rtheys notes above, the systemd method really isn't a practical substitute. If there's an aversion to perpetuating the use of perl for this purpose, might it not be a good idea to re-implement the vncserver script in either bash or python?

**Comment by CendioOssman** [comment]
I'm afraid Perl what not the issue. The problem was that desktop environments and applications now expect a lot of things that we cannot do properly set up as a normal user. We needed to switch to a model where sessions are started by a privileged service.

Unfortunately that meant we didn't have a simple way of letting users start sessions themselves. I don't think it's impossible, but we have no clear plan of how such a feature can be implemented right now.

So I'm afraid what you want is not possible in the current model. Users need to be configured and something privileged (e.g. sudo) needs to get the service going. You might be able to construct your own privileged wrapper that automates this for your users.

**Comment by DaveMielke** [comment]
Systemd is also used to start the session from which "vncserver" is used from. For example, if you first SSH into the machine, and then run "vncserver", then it will inherit the PAM session that was created by sshd. This is why it has worked historically, and why it continues to work if you add the "vncserver" script back (which several distros have now chosen to do).

Yes, there is a question around what happens when you launch multiple "vncserver" from the same session, including in sshd. This still mostly works with a few environment variable changes, but it's not flawless. An easy solution to this problem is to open a second SSH session, and launch the second "vncserver" from the second session.

For my own use cases, I'm still mulling over what to propose back to the community. For now, I just want to clarify that "vncserver" does still work fine as long as you navigate around a few problems. It isn't necessary to always start Xvnc from a systemd service.

**Comment by MarkMielke** [comment]
Systemd is also used to start the session from which "vncserver" is used from. For example, if you first SSH into the machine, and then run "vncserver", then it will inherit the PAM session that was created by sshd. This is why it has worked historically, and why it continues to work if you add the "vncserver" script back (which several distros have now chosen to do).

Yes, there is a question around what happens when you launch multiple "vncserver" from the same session, including in sshd. This still mostly works with a few environment variable changes, but it's not flawless. An easy solution to this problem is to open a second SSH session, and launch the second "vncserver" from the second session.

For my own use cases, I'm still mulling over what to propose back to the community. For now, I just want to clarify that "vncserver" does still work fine as long as you navigate around a few problems. It isn't necessary to always start Xvnc from a systemd service.

**Comment by plembo** [comment]
Thanks to Cendio and Mark for your informative replies. To be honest, for my purposes "ssh -X" is more than enough nowadays. Long gone (thank heaven!) are the days of having to struggle with gui apps from a certain Major Database Vendor,

**Comment by Heng-Zhou** [comment]
@rtheys: Some developer of tigervnc in this thread has no shame for their work. They have no idea of importance of backward compatibility; they feel no shame for the trouble they caused to their users; they even blame Ubuntu for not following their rules. They shamelessly brush off their duty in the name of "open-source", but forgot the basic moral of a software developer.

Of course, these people "has a grave misundertanding" on open-source. They think open-source means they can do whatever they want regardless of users. No, that's not the principle of open-source, that's hegemony, which has nothing to do with open-source. The very principle of open-source is the opposite -- take care of users so that users won't be controlled by these software developers. Fortunately, the principle of open-source itself prevents such hegemony. Ubuntu does not subject to tigervnc's hegemony by still allowing non-root launch of vnc service. Even in Ubuntu 24.04, we can start tiger VNC service without being a root. rtheys, see [here](https://www.server-world.info/en/note?os=Ubuntu_24.04&p=desktop&f=6) for instructions. While tigervnc developers hate Ubuntu, let's appreciate Ubuntu for its good deeds, for it is open-source.
