### ISSUE TITLE
User unable to login locally after user has been registered vncserver.users

### ISSUE THREAD

**Issue by coryhilliard** [TigerVNC/tigervnc#1179]
**Describe the bug**
Once the user has been added to vncserver.users file, the user can't login to the GUI locally anymore. 
(local command line logins still work, so does SSH logins).

**To Reproduce**
1. sudo vi /etc/tigervnc/vncserver.users
2. Add User eg: :2=user
3. Write/Quit [ESC] :wq
4. Try to login using GUI (fails)
5. Remove user from vncserver.users
6. GUI login works again

**Expected behavior**
To be able to login to the server machine as user without having to remove user from vncserver.users every time.

**Client (please complete the following information):**
 - Irrelevant to the issue
 - OS: Fedora 33
 - VNC client: TigerVNC Viewer
 - VNC client version: v1.11.0
 - Client downloaded from: Fedora Repos (dnf install tigervnc)

**Server (please complete the following information):**
 - OS: CentOS 8 Stream
 - VNC server: tigervnc-server
 - VNC server version: v1.11.0-6.el8
 - Server downloaded from: Fedora Repos (dnf install tigervnc-server)
 - Server was started using: sudo systemctl start vncserver@:2

**Additional context**
I initially thought it was because I was using display :1, so I switched everything to display :2, and I still couldn't login.  I then tried removing the user from vncserver.users, and I could login again.  I'm not sure if this is by design, but it seems like it shouldn't work like this.

**Comment by CendioOssman** [comment]
Unfortunately it is by design, similar to how you can't log in two sessions as the same user locally.

It is not our design though, but one of the underlying system. And we're not fans of it. But we're not in a position to change things.

So unfortunately I'll have to direct you to report this to Red Hat. It's unlikely they'll have a quick fix, but if enough users request this use case they might consider supporting it properly.
