### ISSUE TITLE
Alt_L + Shift = Super_L?

### ISSUE THREAD

**Issue by ghollisjr** [TigerVNC/tigervnc#118]
I've found strange behavior with the left alt and either shift key:

(All confirmed with xev and emacs)
When holding shift first and then left alt, a left super was sent.
When holding left alt first and then shift, simply shift and alt were sent.
When doing either of the above using right alt instead of left alt, nothing strange happened.

git commit of tigervnc client and server was
c4bc5a8f0eeacbebb50a2ef79c7b03b64586475a

This may be related to another open bug #8, but I'm not sure so I posted as a new issue.

**Comment by CendioOssman** [comment]
Hmm... This is partly by design. Apparently it's popular for many X11 layouts to send Meta for Shift-Alt. Unfortunately Meta was historically used in some layouts for the Windows key. So we have a compatibility hack that translates Meta to Super. It might be doing more harm than good these days, so perhaps we should re-evaluate that code.
