### ISSUE TITLE
TigerVNC Viewer 1.11.0 crashes when Mac OS 11.X sleeps

### ISSUE THREAD

**Issue by brynowen** [TigerVNC/tigervnc#1201]
When I am connected and leave my computer for 10-20 minutes and return, VNC has crashed.  This apparently coincides with the Mac turning off its display or sleeping.  I am attaching a sample crash log that is displayed each time (this is very common and happens several times a day)
[TigerVNC Viewer_2021-02-10-191222_Bryns-New-iMac.crash.zip](https://github.com/TigerVNC/tigervnc/files/5963149/TigerVNC.Viewer_2021-02-10-191222_Bryns-New-iMac.crash.zip)

**Comment by samhed** [comment]
If you enable logging, what does the vncviewer log say when this happens?

https://github.com/TigerVNC/tigervnc/wiki/Debug-Logs#os-x

**Comment by brynowen** [comment]
Hi Samuel - thanks for checking in on this.  I am running now with logging enabled (actually that page could be updated with correct shell syntax since the commands are not executable as-is) ...

Running this:
/Applications/TigerVNC\ Viewer\ 1.11.0.app/Contents/MacOS/TigerVNC\ Viewer -Log=\*:file:100

Will let you know when it happens again and I have something from the log.

**Comment by CendioOssman** [comment]
I tried to reproduce the issue here on a mac mini but unfortunately couldn't. The crash report shows that it is failing as it tries to show the error message from the connection though.

Do you think you can see if you can find some more specific steps to reproducing this rather than just leaving the machine? We need to be able to reliably produce this at our end.

**Comment by samhed** [comment]
No response.
