### ISSUE TITLE
vncsession always fails out with "Failure daemonizing"

### ISSUE THREAD

**Issue by ajakk** [TigerVNC/tigervnc#1208]
**Describe the bug**
Calling vncsession always results in "Failure daemonizing".

**To Reproduce**
Set up a user with vncpasswd and run `vncsession user :1`.

**Expected behavior**
Expected the server would start.

**Server (please complete the following information):**
 - OS: Gentoo Linux
 - VNC server: TigerVNC
 - VNC server version: 1.11.0
 - Server downloaded from: Github release
 - Server was started using: vncsession

**Additional context**
Building via ebuild and I'm able to reproduce this when building from the plain tarball, and the server worked in 1.9.0. Pretty easy to narrow down where exactly it exits: https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/vncsession.c#L79

**Comment by CendioOssman** [comment]
That's just the parent process, so the true error is in the child process somewhere. Is that the only output you get?

And vncsession should not be called directly, but rather run from a service. How come you are trying to call it directly?

**Comment by ajakk** [comment]
Yes, that's the only output I get.

I'm calling it directly in an attempt to debug it because I'm working on rewriting Gentoo's init script.

**Comment by CendioOssman** [comment]
Please try running it through `strace` in that case so we can see where it fails.

**Comment by ajakk** [comment]
Here you go: 

[log.txt](https://github.com/TigerVNC/tigervnc/files/6069197/log.txt)

**Comment by CendioOssman** [comment]
Sorry, we also need a `-f` flag to `strace` to see what the child process is up to.

**Comment by ajakk** [comment]
Sorry, here you go:

[log.txt](https://github.com/TigerVNC/tigervnc/files/6077091/log.txt)

**Comment by CendioOssman** [comment]
Unfortunately the output is cropped. But I can see it logging before terminating. So you should be able to find something in the journal. Could you have a look there?

**Comment by ajakk** [comment]
I got it via `strace -f vncsession jake :1 &> log`, so I don't think it's cropped. I do see some things in the journal, though:

```
Mar 11 07:36:07 sol vncsession[3043534]: pam_unix(tigervnc:session): session opened for user jake(uid=1000) by (uid=0)
Mar 11 07:36:07 sol vncsession[3043534]: pam_open_session failed: 28 (Module is unknown)
```

**Comment by CendioOssman** [comment]
Alright, that indicates that the pam configuration for vncsession is incorrect. The file included with TigerVNC is a default template which may need to be modified for your system. Unfortunately I'm not familiar with how PAM is configured on Gentoo. Have a look at how other services are configured in `/etc/pam.d` and try to adjust tigervnc's configuration to match. After that everything should hopefully work perfectly. :)

**Comment by zmudc** [comment]
To follow up on this issue over two years later, I can say that on up-to-date Void Linux, I got this error until I commented out the references to pam_selinux.so and replaced the reference to pam_systemd.so with pam_elogind.so in the /etc/pam.d/tigervnc file. This is because there is no SELinux on my installation of Void, and Void uses elogind, a drop-in relplacement for systemd's logind. On Void, it was also necessary to provide an Xsession file at either /etc/X11 or /etc/X11/xinit to make Void compatible with the vncserver perl script. Doing 'sudo ln -s /etc/lightdm/Xsession /etc/X11' fixed that problem for me on Void, and now the tigervnc server is working on Void after also adapting the systemd unit to Void's runit process supervision system.

I don't know how many distros other than Void are lacking both /etc/X11/Xsession file and /etc/X11/xinit/Xsession file, but the current vncserver perl script exits with an error if it cannot find a suitable Xsession file. Might there be a better way to find a suitable Xsession script in the vncserver perl script?
