### ISSUE TITLE
tigervnc-1.10.1 #decperf: Failed to run rfb file: Rect too big

### ISSUE THREAD

**Issue by fffto** [TigerVNC/tigervnc#1209]
Hi.
I'm testing tigervnc-1.10.1 with rfb files from this URL: http://www.turbovnc.org/rfbsessions.tar.bz2
For testing I use decperf and encperf.

Parameters of my PC:
Linux 5.4.0-2.3-amd64 #1 SMP  x86_64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz GenuineIntel GNU/Linux

When I run this:
#decperf bars-16.rfb 
I see the next error message:
"Failed to run rfb file: Rect too big"

When I run this:
#encperf -format=bgr565 -height=1024 -width=1280 rfb_files/bars-16.rfb 
I see the next error message:
"Failed to run rfb file: Unknown message type 5"

These errors also appears in tigervnc-1.11.0.
Where can be the problem?

**Comment by CendioOssman** [comment]
For decperf it's because its the wrong files. It needs the ones called `rfbsessions.turbo.hiqual.tar.bz2`.

encperf works for me, but it fails the same way if I feed it the "turbo" files. You sure you haven't gotten them mixed up?

And what is it you are doing that uses these tools? They're rarely used and don't get that much attention.

**Comment by samhed** [comment]
No response.
