### ISSUE TITLE
Cannot connect to remote desktop for a specific user

### ISSUE THREAD

**Issue by zhouqin007** [TigerVNC/tigervnc#1222]
I installed tigervnc on my pc with windows 10 system.  I have used the tigervnc to connect the remote desktop of our super computer.  However, I can not connect the remote desktop recently. When I input my username and password to the super computer, it shows the following page and nothing happens.
![image](https://user-images.githubusercontent.com/50132542/111874153-1d9e2280-8994-11eb-8a72-f4c54b0cf872.png)

 It seems the problem is related to my username.  Because my colleagues can log on to the remote desktop with theirs username/password from my pc.  Support people of our super computer have checked the issue and did not find the reason yet. I wonder if someone can help me with this issue.

Best,
Qin

**Comment by samhed** [comment]
Looks like you were connected alright, the problem seems to be something in the startup of your remote desktop. Judging from the background image I suspect GNOME isn't starting properly.

I highly doubt this is an issue on your end with the TigerVNC viewer. I'd recommend you to tell your super computer support people to look in the session startup logs on the server side.
