### ISSUE TITLE
Alt-Shift evaluated as XK_Igrave

### ISSUE THREAD

**Issue by czipperz** [TigerVNC/tigervnc#1309]
Windows host is VNCing into Linux computer.

If I press Shift and then press Alt, I expect those two modifier keys are sent, but instead XK_Igrave is sent (/usr/include/X11/keysymdef.h -> 204 / 0x00cc).

If I press Alt and then press Shift, then the modifiers are sent without the weird Igrave translation.

Ex. hold Shift then hold Alt then press 1, then release all 3 and Igrave is sent and the 1 is ignored.
Ex. hold Alt then hold Shift then press 1, then release all 3 and Alt-Shift-1 is sent (Alt-!).

The program I am using doesn't recognize this key sequence and prints an error message.
It's pretty annoying.

Client (please complete the following information):
 - OS: Windows 10
 - VNC client: TigerVNC
 - VNC client version: Not sure
 - Client downloaded from: tigervnc website.

Server (please complete the following information):
 - OS: Ubuntu Linux
 - VNC server: TigerVNC
 - VNC server version: Not sure
 - Server downloaded from: my linux distribution
 - Server was started using: not sure

I'll get back on the exact versions in a few days.

**Comment by czipperz** [comment]
Tigervnc version 1.10.1

**Comment by CendioOssman** [comment]
And the other details? How was this started? What do the logs say?

**Comment by czipperz** [comment]
Yeah I know I'm planning to collect info this weekend when I'm less busy.  Thanks for the help.

**Comment by CendioOssman** [comment]
No response. Closing.

**Comment by LevonX** [comment]
Hello,

I also ran into this problem. We use Wine inside Linux (RHEL). In Wine, it turns out that the keycode 204 is not processed in any way and the Shift_L+Alt_L key combination does not work in the program we are using.

I began to understand deeply and found that in xkb Shift_L+Alt_L, passed through VNC, are defined as virtual keys
`cat /usr/share/X11/xkb/keycodes/evdev
...
        // Fake keycodes for virtual keys
        <LVL3> =   92;
        <MDSW> =   203;
        <ALT>  =   204;
        <META> =   205;
        <SUPR> =   206;
        <HYPR> =   207;
...
`

Please note that the problem occurs when pressing Shift_L+Alt_L, and not vice versa.
PS: I tested it on a clean system, locally, without VNC, and then everything worked perfectly! The keycode returned was 64.

Here is the log you requested above:
Client:
`
Wed Jan 26 13:08:25 2022
 Viewport:    Key pressed: 0x002a => 0xffe1
 Viewport:    Key pressed: 0x0038 => 0xffe9

Wed Jan 26 13:08:26 2022
 Viewport:    Key released: 0x0038 => 0xffe9
 Viewport:    Key released: 0x002a => 0xffe1
`
Server:
`
Wed Jan 26 13:37:09 2022
 VNCSConnST:  Key pressed: 0xffe1
 Input:       keycode 50 down
 VNCSConnST:  Key pressed: 0xffe1
 Input:       keycode 50 down
 VNCSConnST:  Key pressed: 0xffe1
 Input:       keycode 50 down
 VNCSConnST:  Key pressed: 0xffe1
 Input:       keycode 50 down
 VNCSConnST:  Key pressed: 0xffe1
 Input:       keycode 50 down
 VNCSConnST:  Key pressed: 0xffe1
 Input:       keycode 50 down
 VNCSConnST:  Key pressed: 0xffe9
 Input:       keycode 204 down
 VNCSConnST:  Key pressed: 0xffe9
 Input:       keycode 204 down
 VNCSConnST:  Key pressed: 0xffe9
 Input:       keycode 204 down
 VNCSConnST:  Key pressed: 0xffe9
 Input:       keycode 204 down
 VNCSConnST:  Key pressed: 0xffe9
 Input:       keycode 204 down
 VNCSConnST:  Key released: 0xffe9
 Input:       keycode 204 up
 VNCSConnST:  Key released: 0xffe1
 Input:       keycode 50 up
`

**Comment by CendioOssman** [comment]
That is unfortunately expected. VNC doesn't guarantee correct key codes, only correct keysym. You'll need to use the `RawKeyboard` setting if you want correct key codes. That will however mean that keysyms are no longer guaranteed. There is no way to do both.

Also note that we have some compatibility adjustments, like 3b532f87b26d791b0b64b87aa39141d1a81098e8, 35cc8d53f9fe8915da3c5b99dee92243c7147ec6 and 0255e1b004fe6518c650e9d12b8862c2b2dad30b that mitigate problems specifically for Alt and Shift.

**Comment by LevonX** [comment]
Thank you very much for your answer, this fully explains why the keyboard shortcut does not work for us in Wine.
The only thing I would like to clarify is the combination Shift_L + Alt_L will always return keycode 204 and only this combination will return keycode 204?

**Comment by CendioOssman** [comment]
No, that will depend entirely on the keyboard layout in the server. So there are no guarantees. The server will pick the key code that matches the symbol.

**Comment by LevonX** [comment]
Got it, thanks a lot for the info.
