### ISSUE TITLE
fcitx failed in vncviewer

### ISSUE THREAD

**Issue by ccl-private** [TigerVNC/tigervnc#1371]
**Describe the bug**
I cannot change the input method in VncViewer, but the local pc can do it correctly.

**To Reproduce**
1. install and setup VncServer following this airtcle:https://linuxize.com/post/how-to-install-and-configure-vnc-on-ubuntu-18-04/
2. run VncViewer succeed.
3. install fcitx5, and modify Xstartup file 
![image](https://user-images.githubusercontent.com/36214675/141272363-54e52276-46f5-42d6-9744-af150cf2096f.png)

4. reboot my PC and use VncViewer to connect
5. fcitx5 run successfully
6. cannot change the input method.
![image](https://user-images.githubusercontent.com/36214675/141273064-35a1ac4c-0f3d-46a9-a240-fd513e86625d.png)

**Expected behavior**
can change fcitx5 input methods.

**Screenshots**

**Client (please complete the following information):**
 - OS: Windows 10
 - VNC client: vncviewer
 - VNC client version: 6.19.715
 - Client downloaded from: https://www.realvnc.com/en/connect/download/viewer/

**Server (please complete the following information):**
 - OS:debian11
 - VNC server: TigerVNC
 - VNC server version: 1.11.0
 - Server downloaded from: my Linux distribution
 - Server was started using: vncserver

**Additional context**

**Comment by ccl-private** [comment]
In local PC, fcitx5 works well.

**Comment by CendioOssman** [comment]
Unfortunately standard VNC doesn't support input methods in a decent way. The reason is that VNC is designed to use the keyboard configuration of the client, not the server. And the protocol only has support for "normal" keyboard input.

What you can try is enabling the "raw keyboard" extension in the server by specifying `-RawKeyboard` to `vncserver`. However this extension is not supported by RealVNC so you'll have to use a different client. Ideally the TigerVNC client.

**Comment by ccl-private** [comment]
thank you ~ I will have a try~

**Comment by ccl-private** [comment]
![image](https://user-images.githubusercontent.com/36214675/141421177-7f65edca-6388-4b62-ae5e-67080810d00b.png)

**Comment by ccl-private** [comment]
@CendioOssman problem solved. standard VNC is fine. the problem is in "~/.vnc/xstartup" file. after setting above, the input method works well.
