### ISSUE TITLE
"VNC authentication enabled, but no password file created."

### ISSUE THREAD

**Issue by arfonrg** [TigerVNC/tigervnc#1393]
SlackwareARM (kernel 5.15.6-v7), TigerVNC (1.12.0)

Newly installed TigerVNC on 3 different RPis.   All are returning:
 "VNC authentication enabled, but no password file created." 
 ...when trying to start the server.

vncserver would not make the password file so I 'touched' them.  The server still would use the files so I set them (and then .vnc directory) to 777.  Still gives me the same error.

user@darkstar:~$ ls -la .vnc
total 8
drwxrwxrwx 2 user users 4096 Dec 10 13:23 ./
drwx--x--x 5 user users 4096 Dec 10 13:23 ../
-rwxrwxrwx 1 user users    0 Dec 10 13:23 passwd*

user@darkstar:~$ vncserver :1
VNC authentication enabled, but no password file created.

**Comment by arfonrg** [comment]
UPDATE:  Setting a password with vncpasswd creates the passwd file and gets vncserver to work.   But, I have never had to do this before and I don't have to do this on other machines.

**Comment by CendioOssman** [comment]
TigerVNC 1.12.0 does not include a `vncserver` command, so I'm not sure what it is you are running. Are you sure it isn't something else?

The default behaviour has always been to require a password, so I'm not sure how you got things running before. Perhaps you were using something different than our scripts then as well?

**Comment by CendioOssman** [comment]
No response. Closing.

**Comment by shuuji3** [comment]
Hi, recently, I encounter the same error and it took some time to find out that the cause of the issue was the permission of `passwd` file. In my case, I tried to create `passwd` by shell script automatically and didn't set the permission correctly.

This error message is printed out here: https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/vncserver.in#L151-L156 and it will be raised by either of two cases:
- there is no `passwd` file at the correct place
- `passwd` has accessible by other users

In the above case, the `passwd` had permission 777, so it raised the error. But `vncpasswd` command sets the permission of `passwd` to 600 by default.

I feel that the error message is a bit misleading when the file actually exists but has the wrong permission. I assume that a-griff might have changed the permission to 777 because it could have file access issues due to limited permission.

I'll create a PR to make the message more clear.
