### ISSUE TITLE
Tigervnc uses llvmpipe instead of amdgpu driver

### ISSUE THREAD

**Issue by nzagni91** [TigerVNC/tigervnc#1465]
Hello, I would like to report this issue I am experiencing on RHEL 8.5 with tigervnc.

I have a AMD Radeon Pro WX 3200 with the amdgpu driver installed. 
I use the machine from a Windows client remotely with tigervnc via an ssh tunnel. 
When running the command `glxinfo | grep OpenGL`  I visualize the following 
```
OpenGL vendor string: Mesa/X.org
OpenGL renderer string: llvmpipe (LLVM 12.0.1, 256 bits)
OpenGL version string: 4.5 (Compatibility Profile) Mesa 21.3.0-devel
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
```
indicating that llvmpipe is in use instead of amdgpu. This does not occur when connecting directly to the machine from the local terminal and monitor (i.e., amdgpu is used).

From this I suspect the issue lies with tigervnc rather than to the driver or xserver, but I am not completely sure if this is the case.

Does anyone have an hint on how to solve this? 
Thanks

**Comment by CendioOssman** [comment]
I'm afraid that is how the architecture of OpenGL under X11 works. The graphics driver and the OpenGL driver need to work in tandem. And since the VNC session is independent of any local graphics ports, it cannot use the GPU's OpenGL driver.

The only way around this that I know of right now is VirtualGL, which does some magic to redirect things to make acceleration work in a VNC session. Please have a look at that if you need to use the GPU.

**Comment by nzagni91** [comment]
Thank you for your answer. I will try VirtualGL and see if that fixes the problem.
