### ISSUE TITLE
Vncviewer - show mouse symbol rather than dot when no cursor .  [$100]

### ISSUE THREAD

**Issue by ahmedyo** [TigerVNC/tigervnc#1483]
In vncviewer - there is an option for "show dot when no cursor " , though this is very helpful . 
its  unusable , while using VNC client , remote mouse lags and the dot which creates a perception of speed is pretty invisible . 

I think in vncviewer project : 

adding an option to show imaginary mouse pointer or an option to replace dot with icons similar to mouse cursor will be a good add . 

I know this may not be a valid request , but i plan to propose a bounty and bountysource expects a issue url :) 

https://app.bountysource.com/issues/109362423-vncviewer-show-mouse-symbol-rather-than-dot-when-no-cursor

Bounty of 100 USD - i am ok , even if i can get a working local copy .

**Comment by ahmedyo** [comment]
https://app.bountysource.com/issues/109362423-vncviewer-show-mouse-symbol-rather-than-dot-when-no-cursor

**Comment by CendioOssman** [comment]
Could you describe your setup a bit more? So we can better understand the circumstances where things aren't working well for you.

**Comment by krystof1119** [comment]
I've taken a look at this and I believe to have added the feature requested - a PR will follow soon.

I've also uncovered a bug in the Java version of vncviewer related to cursor rendering, which I will address in a separate PR (and create a separate issue for).

**Comment by ahmedyo** [comment]
To explain this better i really need to upload a  video . 

Here is my situation , i connect to vnc server using tigervnc . 

I have a latency of around 315 milli seconds between my computer and vnc server . 
What happens is - every time i move mouse , mouse pointer drags slowly . as a developer this gives me a feeling of slow response . 

So currently instead of following the mouse of vnc server (remote host ) , what i do is i follow the dot (dot is local and no network) . Eventually remote cursor (with usual latency follows my dot ) . 

What i was hoping to achieve was : 

- instead of dot , if get either a larger dot or a mouse icon , it would be ease for me to work .

**Comment by ahmedyo** [comment]
@krystof1119 @CendioOssman  - Sorry for the delayed response .

**Comment by CendioOssman** [comment]
No response. Closing.

**Comment by roberestarkk** [comment]
This is absolutely something I'd also like to be able to do. 
I just can't make my brain go "pointer isn't mouse, dot is mouse", so I'm having issues with over-shooting my intended destination (by about a dot-width), and having to wait for the server cursor to arrive anyway, or just having to move the mouse slower than I want to because it's not quite following where I think it should be based on my physical movements.
(Gif of TigerVNC with dot, the dot for some reason is freakishly big in the capture, but is normal-sized in the actual screen):
![](https://i.imgur.com/7BeLovJ.gif)

Other viewers like TurboVNC do have a proper pointer-looking image as the 'dot', which I've found feels quite a bit easier to subconsciously use as a kind of promise of "This is where the remote pointer will eventually be, feel free to send a click", but they lack other features that makes Tiger the superior choice.
(Gif example of the TurboVNC local pointer)
![](https://i.imgur.com/5YjLHb2.gif)

I'm not sure whether it's just that the dot is too small (which doesn't come through on the gifs of course) or whether it's a bit of lingering uncertainty over which part of the dot is the 'point', or whether it's because the dot isn't a system-level cursor so even it's lagging slightly behind where the 'actual' cursor is, or it's a mental thing about what I'm used to cursors looking like, or some combination of the above, but the viewer where the client cursor is an actual pointer just feels better.

I wouldn't be against the pointer being a different colour to differentiate it from the remote cursor either, as it is admittedly more difficult to tell at a glance which is the client cursor and which is the server. That's something I can easily fix in the server by changing the windows cursor colour setting though, since I never access it outside of VNC.

Also, to be clear, hiding the cursor on the clientside entirely is something I've tried, but it feels even ickier, even with the relatively slight amount of latency.
