### ISSUE TITLE
Resize remote session on connect

### ISSUE THREAD

**Issue by fenopa** [TigerVNC/tigervnc#1527]
So I downloaded latest nightly build "vncviewer-1.12.80.exe" but I see that you removed two options:

- Resize remote session on connect
- Resize remote session to the local window

Why would you remove these options? "Resize remote session on connect" was so useful, I'm always using it. Please don't remove that at least, please add it back.

**Comment by CendioOssman** [comment]
We thought it was so useful that remote resizing is now always enabled. Is it not resizing correctly for you?

**Comment by fenopa** [comment]
> We thought it was so useful that remote resizing is now always enabled. Is it not resizing correctly for you?

The problem is I want to put exact resolution to "Resize remote session on connect" each time and I want to change it time to time. I mean I want to make it start with some standard resolutions like 1366x768, 1280x720, 1920x1080 etc.. I was even gonna suggest to make it possible to add some predefined values there and select it from a combobox but you removed it entirely.

**Comment by CendioOssman** [comment]
Ah. Specifying exact resolutions was something we considered more niche, so that is no longer available in the GUI. You can still reach this functionality through the command line, though, using the `-DesktopSize` argument.

I'm curious what use cases you have that require specific resolutions. Would you mind elaborating a bit more on how you are using TigerVNC?

**Comment by CendioOssman** [comment]
No response. Closing.

**Comment by capfan2** [comment]
I would also like to add a vote for bringing back "Resize remote session on connect".  This was very useful on Macbook retina displays for forcing a session using the actual physical resolution of the display versus the scaled resolution that gets set when maximizing the window.

**Comment by CendioOssman** [comment]
Which VNC server are you using in that case? The built-in one in macOS doesn't have any resizing support.

**Comment by capfan2** [comment]
I am running TigerVNC server on a Linux host and using the Mac viewer.  I suppose the underlying issue is that there is no obvious way to take advantage of the full resolution of the MacBook retina display just by maximizing the viewer window.  This is why being able to set the exact resolution was needed.
________________________________

**Comment by CendioOssman** [comment]
I don't quite understand how manually setting the resolution would help, as you'd just get something that gets scrolled instead?

Anyway, high DPI support is #369, so please have a look there for any future improvements.

**Comment by dwarf007** [comment]
I am in an environment where we have a system running a VNCserver with a geometry set to a specific default workstation screen layout. We however allow other users (that have different monitors and screen resolutions) to access the same system. When they do, they should not use the resize remote option.
In order to do so, we instructed them to un-tick these options in the past:
![image](https://user-images.githubusercontent.com/2540393/219372514-9d27961f-d3ea-445f-a958-1a248d69c567.png)

If someone did by mistake change the resolution, we could remotely change it back to the correct screen resolution using this option:
![image](https://user-images.githubusercontent.com/2540393/219372717-12ed005d-c21f-42ed-9384-0e99e0c07d35.png)

With the latest tigerVNC client (1.13.0), we however lost this functionality:
![image](https://user-images.githubusercontent.com/2540393/219372843-dee9d3d8-3d97-4a2d-a628-c94c7d10c545.png)

and by default the -RemoteResize is set to 1.
We can change this via command line, but most of our users would not know how to change such settings and were comfortable using these menu options.

**Comment by CendioOssman** [comment]
I'm afraid I don't understand why the session size sometimes needs to be fixed, and sometimes doesn't. Would you mind describing more what problems you are fixing by working in this way?

**Comment by dwarf007** [comment]
We work in an environment, where operator staff access specific remote machines from a thin-client using tigerVNC. 
The thin-client has two monitors. By default the tigerVNC server of the remote machine is started with a fixed size of 3840x1080. 
It could happen that a support staff connects to that remote machine in parallel to the operator, either to monitor or to help troubleshooting something. This may be done from a laptop, or another system that is not a thin-client (i.e. NOT 2 monitors in 3840x1080). In this case, if we cannot disable the RemoteResizing via the graphical user interface we will mess up the display of the operator although the operator staff will be confused, although the operational priority is on that person and that 2 monitor thin-client (3840x1080). 
I hope it's clearer, otherwise I can try to give more details.

**Comment by CendioOssman** [comment]
Ah, I see. So this is about secondary users not messing up the screen layout for the primary users. That makes sense.

Ideally, I think this should be enforced by the server. We already have some policy system in the form that you can have a normal password, and a "view only" password. That system should ideally be flexible enough so you can apply other policy decisions.

**Comment by dwarf007** [comment]
The secondary user may need to control the Graphical User Interface, therefore the "view only" option is not good. The secondary user may become prime user and choose the "resize remote to the local window" temporarily, before setting it back to 3840x1080.
These option to control remote resizing from the client, were the reasons why we chose tigerVNC over realVNC, vnc connect etc.

**Comment by ppascher** [comment]
Another vote for putting the option back in the UI (for convenience since the CLI parameter works as well).
I have to use shortcuts (Win + x) which only get passed to the remote PC when TigerVNC is fullscreen so I often switch back and forth. The automatic resize disrupts this workflow. Also I like to have my VNC window slightly larger than the remote workspace to prevent slight misclicks around the edges to focus the window behind my client.

**Comment by hporter3** [comment]
Yet one more vote to add the option back in to the UI.  I have been using an older version and so I didn't realize this option had been removed.
The problem I have is that I'm using some CAD software that tends to freak out when the size of the vnc window is resized.  The fonts get all messed up and it becomes unusable.  The fixed screen size prevents that from happening.  
Please consider adding it back.
Thank you

**Comment by spectrallypure** [comment]
+1 to the request of bringing back these options. In [our particular use case](https://github.com/TigerVNC/tigervnc/issues/1877#issuecomment-2528539707), we **do not** want the remote session to be resized to the local display; having this option customizable through the GUI (instead as a command-line parameter) was very convenient. Please bring these back!

**Comment by spreiter** [comment]
I would also be in favor of having this option again. Especially because it is mentioned (https://github.com/TigerVNC/tigervnc/issues/398#issuecomment-272879610) that only options in the GUI are available in the config file.

In my institute we use shared machines a lot and specifying those options every time is quite annoying. I know I might use `.tigervnc` files, but I don't want to have a file for each host.

PS: Would also be great if the documentation of the `vncviewer` is updated that **not** all options are supported in the config file.

**Comment by chrisbadger** [comment]
+1 for adding back the RemoteSize[=0] option to the GUI and/or config file.  We often do a quick demo/meeting on a shared display and and the auto-resize causes issues when sharing/viewing screens with others in my org.   

I thought other users were manually fiddling with the display size but it turns out it was automatic for them.  I didn't realize because I was on a different VNC viewer client that didn't auto-resize.  I just upgraded to a recent tigervnc version and was disappointed to find that I couldn't even store RemoteResize=0 in my default.tigervnc file (despite the docs indicating otherwise...).

**Comment by alshdavid** [comment]
I'm on windows 10 and the client does not resize to fit the window and has scroll bars

<img width="1197" height="910" alt="Image" src="https://github.com/user-attachments/assets/489e38f3-0883-47f7-b75d-a458954116df" />
