### ISSUE TITLE
[website] Donation site is down

### ISSUE THREAD

**Issue by macias** [TigerVNC/tigervnc#1548]
This is bug report against website not code.

For at least 2 months now the donation website is down with generic info " We are sorry to inform you that the SALT platform has been temporary closed for technical reasons."

So by definition no donation is possible.

**Comment by CendioOssman** [comment]
I'm afraid I cannot see any broken links. Which link are you referring to?

**Comment by macias** [comment]
Links are not broken, the website is. TigerVNC donations go through https://salt.bountysource.com/checkout/amount?team=tigervnc and this website is not operational for at least 2 months now with the message as I quoted in original post.

**Comment by CendioOssman** [comment]
Ah, I see what you mean. We've never had too much interest in donations to the project itself, since all current maintainers are otherwise employed. What we are trying to get from Bountysource are the bounties, which are for specific bugs or features.

I think I've been able to disable the general donations for now, which should avoid confusion.

Do you think there are any specific bugs or features you might be interested in sponsoring, instead of a general donation to the project?

**Comment by macias** [comment]
Thank you for reply. I am a weekend user so I don't have demanding needs. I wanted to donate some to basically express "thank you" in more meaningful way than just words :-) But I checked the list of bounties and this one:
https://github.com/TigerVNC/tigervnc/issues/839
could be a fit, I would say no to performance improvement even if I am not affected.

But how I can donate here? Via github?

**Comment by CendioOssman** [comment]
You should be able to add to the bounty via bountysource. It only seems to be their general donation system (SALT) that is done. I get a paypal checkout option if I click the "$156 open bounty" link on that issue at least.

**Comment by macias** [comment]
Thank you, done :-).
