### ISSUE TITLE
Open browser during vnc remote connection

### ISSUE THREAD

**Issue by mdatres** [TigerVNC/tigervnc#1582]
Dear all, 

I'm trying to open a browser during a tigervnc remote connection. I cannot see the firefox icon and running firefox from terminal I end up with this error:

/user.slice/user-1001.slice/session-58.scope is not a snap group

Can you help me? 

Thanks in advance, 

Max

**Comment by CendioOssman** [comment]
Please fill out the issue form properly.

**Comment by mdatres** [comment]
Thanks for the quick reply. I try to explain better what I mean. I opened a TigerVNC gnome session. Everything worked fine, I'm able to open folders and also create files. I have just a problem with firefox. I would like to open firefox in the vnc session, but it doesn't work. Indeed, when I run the command `firefox` in the terminal, I end up with the following error `/user.slice/user-1001.slice/session-58.scope is not a snap group`. Below I attach my xstartup file:

> #!/bin/sh 
> [ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
> [ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
> vncconfig -iconic &
> dbus-launch --exit-with-session gnome-session 

To open the service I used the command `tigervncserver -xstartup ~/.vnc/xstartup`. Hope now the problem is clear, if not let me know. I want to thank you again. 

Best, 

Max

**Comment by CendioOssman** [comment]
I'm afraid that startup script (`tigervncserver`) is from Debian/Ubuntu, and not from us. As such, it's not something we know the details of and is not something we can help you with.

I suggest filing an issue with your distribution and see if they can help.

You can also try using our packages from the release page. Note that they use a service instead of a script to launch sessions.
