### ISSUE TITLE
Missing 1.13.0 stable?

### ISSUE THREAD

**Issue by Neustradamus** [TigerVNC/tigervnc#1596]
Hello @TigerVNC team,

I think that there is a missing part on GitHub, the 1.13.0 stable has been released but nothing here.

Last stable is 1.12.0 (Nov 10, 2021):
- https://github.com/TigerVNC/tigervnc/releases/tag/v1.12.0

Last unstable is 1.13.0 Beta (Dec 23, 2022):
- https://github.com/TigerVNC/tigervnc/releases/tag/v1.12.90

SF: https://sourceforge.net/projects/tigervnc/files/stable/1.13.0/

Thanks in advance.

**Comment by CendioOssman** [comment]
Patience, my dear. :)

It takes some time for us to get everything in place. We'll send out an announcement once everything is done.

**Comment by Neustradamus** [comment]
@CendioOssman: My ticket has been closed as not planned?
The release on GitHub is not planned?

The 1.13.0 release is already out on Sourceforge... but there is a problem on the git source?
The tag must be done before a release build...

**Comment by CendioOssman** [comment]
The process is that we first create a tag, so that the builds have something to target. We then have to get all the different builds done and uploaded to sourceforge. Once that is in place, we can create a release on GitHub, based on the tag. And as a final step, we send out an announcement.

All of these things take time, and no one is able to work full time on it. So the whole process might take a few days.

**Comment by Neustradamus** [comment]
@CendioOssman: Yes the tag was not created before the upload on Sourceforge...

**Comment by bphinz** [comment]
?  The tag (d9e89d9) was created on February 3rd and the binaries were
uploaded to sourceforge on February 5th

**Comment by Neustradamus** [comment]
@bphinz: When I have done the ticket (2023-02-07), the "tag" and "release" were not here!
