### ISSUE TITLE
How to start vnc server as a regular user if vncserver script is considered deprecated

### ISSUE THREAD

**Issue by jhgit** [TigerVNC/tigervnc#1597]
CendiOssman wrote on Mar 7, 2022 in issue #1438:
> There's a HOWTO included now to get you started with the new method. You can find it here:
> 
> https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/HOWTO.md

That HOWTO is written for unix-ish platforms that have systemd.  In the systemd unit file, it points to using vncsession.

But...

    /usr/local/sbin/vncsession someuser :1
    This program needs to be run as root!

The HOWTO could be updated, of course.  But with what?  If vncserver is deprecated, is the recommended way to start a vnc server as a regular user now going back to calling Xvnc directly?

This (no non-deprecated way to start a vnc server except calling Xvnc directly) is true even of systems that DO user systemd - using a user controlled systemd unit (systemd unit in ~/.config/systemd/users invoked via `systemctl --user start vncserver@:1`) will fail the same way because the systemd vncserver unit ultimately calls vncsession.

When I opened issue #1438, I was focused solely on the case of admistrator control of vncserver startup (i.e., automated sessions that start on boot).  But the non-boot start / stop of vnc server sessions is an equally important use case.

What's the right path forward for supporting regular users' on-demand start/stop of vnc servers?  Would it be to modify vncsession to remove it's 'root only' fiat?  Un-deprecate / improve the vncserver script (or revert to something like the version before the 'Start sessions via PAM' [commit](https://github.com/TigerVNC/tigervnc/commit/1af1cfdf8709dd1a5574efa19fb4f0e68a98021e))?  Require users to directly call Xvnc (and `kill` the vnc server PID via `cat ~/.vnc/xxx.pid`)?  Maybe that's fine, but it's something of a UX regression after decades of fingers being familiar with the vncserver entry point.

_Originally posted by @jhgit in https://github.com/TigerVNC/tigervnc/issues/1438#issuecomment-1427120821_

**Comment by jhgit** [comment]
FreeBSD, for instance, has kept around an older version of [vncserver](https://cgit.freebsd.org/ports/commit/net/tigervnc-server/files/vncserver.ports?id=e6d3d07a90f58a4e93a2dee15a631be24d3db1f6), probably because the direction of the changes for vncserver are too restricting.  Not every situation needs PAM.  Not every situation calls for sessions that run from systemd/init.  Not every environment is running a display manager.

**Comment by jhgit** [comment]
I hacked up the current vncserver script just to allow it to start a plain vnc server - no desktop file, no Xsession needed:

[vncserver.diff.txt](https://github.com/TigerVNC/tigervnc/files/10717411/vncserver.diff.txt)

I'm not suggesting that be committed, of course.  But it is just to illustrate what pre-condition assumptions could be reconsidered for keeping a simple use case (e.g., Xvnc + xterm) working.  That seems like it is still useful.

**Comment by jhgit** [comment]
> The old way works for some simple cases, yes. But it breaks for the more common ones, like starting a normal desktop.

Thanks for the reply.

The old vncserver works fine for me starting a normal desktop.  Just put the startup script for the preferred desktop environment in ~/.vnc/xstartup - no problem, no special knowledge required other than knowledge of the xstartup script.

Can you provide an example how it can break?  I am wondering if there is a path to allowing the current vncserver (as modified recently with all the hooks to support a desktop environment world) to be peacefully updated to also support more basic environments.  Is the project is open to considering possible modifications to support such a goal?

**Comment by CendioOssman** [comment]
> Can you provide an example how it can break?

GNOME¹ has probably been the most picky environment. It expects to be running in a user slice, so it has an id for the session, and it has a user systemd instance for launching things.

If you start the session from a console, then you generally have those (as the console is in a user session). But things can get wonky once you log out and expect the VNC server to continue in the background.

Starting it from a service is probably where it misbehaved the most, as it will be running under some service slice instead of a user.

¹ Other desktop environments are following, though, so it's not just a GNOME issue

> Is the project is open to considering possible modifications to support such a goal?

Yes, but it would need to fit with what is considered current requirements. Not just that it seems to work in a quick test. One such requirement is that the session is properly set up in systemd. Which is the big blocker where we are not aware of any unprivileged mechanisms.

**Comment by wohali** [comment]
Just a data point here for posterity.

My company's client uses racks of traditional X servers to host vncservers for hundreds-to-thousands of users who run their sessions in the cloud - these are all XFCE4.

Newer versions of tigervnc-server broke the ability to host this way because of the systemd requirement. It is both impractical and unreasonable to either:

* run 1,000 tigervnc-server sessions on every available vncserver host, or
* write other software that dynamically balances load across vncserver hosts and changes the systemd mapping for each user across literally hundreds of servers.

For now we have deployed @jhgit 's solution of running the 1.10 script, which allows for a seamless upgrade of those machines. However, it would be nice, going forward, to have a supported solution for desktop environments or X servers that do not require a systemd user session.

I think the weakest promise we'd ask from TigerVNC is to simply not mandate that user session in the lower tier processes; we can continue to work around this choice if this statement by @CendioOssman remains true:

> Users that have a custom setup where things could still work with the old script should be users who are knowledgable enough to be able to call Xvnc directly and whatever more they want (like xterm).

by writing our own launch script (or modifying the ~v1.10 script to continue to work for our needs).

Thank you for your time!

**Comment by htInEdin** [comment]
For those who search for "tigervnc" "not root" and/or "Only console users are allowed to run the X server", the above suggestion by @wohali is still true for 1.15.  Here's what worked for me:

1. Open [vncserver v1.10](https://github.com/TigerVNC/tigervnc/blob/1.10-branch/unix/vncserver) and download or grab it;
2. Edit by hand to
    - replace `Xvnc` with `Xtigervnc` and `vncpasswd` with `tigervncpasswd`
    - comment out `$default_opts{rfbwait} = 30000;`

Unless otherwise hacked, both `config` and `xstartup` will be looked for in `$HOME/.vnc,` _not_ under `$HOME/.config/tigervnc`.

Then whatever worked when you used to be able to use `(tiger)vncserver`as a non-root user should work again.  In particular, you should be able to `ssh` from home to a host at work via a VPN, use `vncserver` to launch a server instance there, exit back home and run a vnc viewer to give you access to an X desktop at work.
