### ISSUE TITLE
 Image:       Failed to create SHM image, falling back to Xlib image

### ISSUE THREAD

**Issue by puneet336** [TigerVNC/tigervnc#1630]
**Describe the bug**
I am trying to use the tiger vnc 1.13.0 but i am getting issues.

```
usr/bin/x0vncserver -passwordfile ~/.vnc/passwd

Tue May 16 00:58:15 2023
 Geometry:    Desktop geometry is set to 3840x1440+0+0

Tue May 16 00:58:17 2023
 XDesktop:    Using xorgkbd codemap
 XDesktop:

Tue May 16 00:58:19 2023
 XDesktop:    XTest extension present - version 2.2

Tue May 16 00:58:20 2023
 Main:        Listening for VNC connections on all interface(s), port 5900

```

![Uploading image.png…]()

<img width="313" alt="image" src="https://github.com/TigerVNC/tigervnc/assets/5935825/eecd40d1-aeff-4363-97b9-34b0c6ae848b">

**To Reproduce**

**Expected behavior**
I was expecting to the the VNC screen.

**Screenshots**
<img width="440" alt="image" src="https://github.com/TigerVNC/tigervnc/assets/5935825/15e96f13-5a42-4481-a99f-4601f0654883">

after ~2-3 minutes i see a black screen - 
<img width="1917" alt="image" src="https://github.com/TigerVNC/tigervnc/assets/5935825/b4dbb07c-314e-432f-8cd4-bba9783df374">

**Client (please complete the following information):**
 - OS: [e.g. Windows 8.1]
 - VNC client: [e.g. TigerVNC, or UltraVNC]
 - VNC client version: [e.g. 1.8.0]
 - Client downloaded from: [e.g. my Linux distribution]

**Server (please complete the following information):**
 - OS: CentOS7
 - VNC server: Tiger VNC
 - VNC server version: 1.13.0
 - Server downloaded from: https://sourceforge.net/projects/tigervnc/files/stable/1.13.1/el7/RPMS/x86_64/
    i had download the rpm and untarred the required binary files.
 - Server was started using: usr/bin/x0vncserver -passwordfile ~/.vnc/passwd

**Additional context**
```
Tue May 16 02:06:35 2023
 ComparingUpdateTracker: 5.5296 Mpixels in / 0 pixels out
 ComparingUpdateTracker: (1:inf ratio)
 Geometry:    Desktop geometry is set to 3840x1440+0+0
Xlib:  extension "MIT-SHM" missing on display "localhost:10.0".
 Image:       XShmQueryVersion() failed
 Image:       Failed to create SHM image, falling back to Xlib image
Xlib:  extension "MIT-SHM" missing on display "localhost:10.0".

Tue May 16 02:08:04 2023
 Image:       XShmQueryVersion() failed
 Image:       Failed to create SHM image, falling back to Xlib image
Xlib:  extension "MIT-SHM" missing on display "localhost:10.0".
 Image:       XShmQueryVersion() failed
 Image:       Failed to create SHM image, falling back to Xlib image

Tue May 16 02:08:06 2023
 ComparingUpdateTracker: 0 pixels in / 0 pixels out
 ComparingUpdateTracker: (1:-nan ratio)
```

**Comment by CendioOssman** [comment]
Are you starting `x0vncserver` via ssh? It seems to be connecting to a tunnelled X server, rather than a local one. It's generally best to start `x0vncserver` inside the session you want to export.

**Comment by puneet336** [comment]
We have a Shared computing facility wherein i have been alotted a specific system. and i can access that system only via ssh.
ssh server1
server1] usr/bin/x0vncserver -passwordfile ~/.vnc/passwd

I did not understand how i can start the x0vncserver locally?

**Comment by CendioOssman** [comment]
Ah, I understand the issue then. x0vncserver will use the X server specified in the environment it is started. In your case, it is started in an ssh session, so it is likely trying to use the X tunnel that ssh has set up. Which is a bit weird, given that you are on a Windows client. But perhaps you have an X server there as well?

I can't say what the correct method is because I'm unsure what you are trying to achieve. Would you mind describing your setup and what you are trying to do? If we understand it better, we can hopefully point you in the right direction.

**Comment by CendioOssman** [comment]
Ah, I see. I'm afraid `x0vncserver` is an entirely different type of server than `vncserver`, so it's not what's appropriate here.

In modern TigerVNC the session needs to be started using a service, not the `vncserver` command. The primary reason being reliability issues like you mention. Since it is a system service, it's not something you can set up as a user. You'll need to get in touch with your sysadmin to configure a VNC session for you. Some instructions can be found in this HOWTO:

https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/HOWTO.md

**Comment by snbuch** [comment]
I have this exact same issue. The setup described by puneet336 is very common in software organizations. I am not sure what's the technical issue in allowing more than one vncserver to run on the same Linux server but it would be nice if I can run my own version on the vncserver rather than just what the sysadmin has provided. Is there really no way of running my own version of vncserver? Won't there be a way for this vncserver to connect to a window manager and provide menu and terminal windows to the user?

**Comment by snbuch** [comment]
Did more research and it seems Xvnc is what we need to be running but it needs to be started by vncsession and vncsession needs to be run as root. It seems vncsession is to be started as a system service but that does not seem to be a hard requirement. 

My guess is that it needs to be run as root to be able to check if someone else is already using the X11 display that will be created by this session.

**Comment by CendioOssman** [comment]
The requirement actually comes from the system. Environments like GNOME expect to be in a user session, and those can only be created by stuff running as root. Starting it from an existing user session can sometimes work, but will generally break eventually. So we haven't catered to that option.
