### ISSUE TITLE
TigerVNC Viewer does not resize window after connect.

### ISSUE THREAD

**Issue by mky** [TigerVNC/tigervnc#164]
OS: Windows 8.1 Pro
Affect: TigerVNC Viewer >= 1.4.0

Since version 1.4.0 TigerVNC Viewer does not resize window after connect to TigerVNC Server. It ignore option: Screen -> Resize remote session on connect.
Latest working version is 1.3.1.

**Comment by CendioOssman** [comment]
Is the server the same version in both cases? And are you using Xvnc or the Xorg module?

**Comment by mky** [comment]
Currently the server is running TigerVNC 1.4.3 (OS: FreeBSD 10.1 / amd64). I am using Xvnc.

**Comment by CendioOssman** [comment]
Does it resize when you change the size of the local window? (provided you have that setting turned on)

**Comment by mky** [comment]
Yes it does. Only the automatic resize after the connect is not working.

**Comment by CendioOssman** [comment]
Great. That means that all the technical underpinnings are working. It's just not triggering properly for some reason.

I can reproduce the issue here, and it's not just the Windows client. Oddly enough it works fine when you specify things on the command line. So the bug must be in the Options dialog.

**Comment by CendioOssman** [comment]
Should be fixed in 135906e. Please try the next nightly build and see if it works for you as well.
