### ISSUE TITLE
No ZlibLevel parameter

### ISSUE THREAD

**Issue by twaugh** [TigerVNC/tigervnc#166]
Since commit 4870081 the ZlibLevel parameter has not been available in `vncviewer`.

Original report:
  https://bugzilla.redhat.com/show_bug.cgi?id=1213199

**Comment by CendioOssman** [comment]
I'm not sure we have a fixable bug here. The issue is that ZlibLevel is being interpreted as the host name. We could make sure both mentioned cases fail, but there's no sane way to make it ignore unknown options and still identify the host.

(and no, I don't think it's a good idea to undo the bug fix and reintroduce pointless options to the client)

**Comment by twaugh** [comment]
Oh, so in fact ZlibLevel is not a valid vncviewer option in the first place?

**Comment by CendioOssman** [comment]
Nope. It was a setting for one of the encoders (i.e. only used in the servers). There were a few others like this that leaked in from the encoders into the client.

**Comment by twaugh** [comment]
Ah, OK, sorry for the noise then.
