### ISSUE TITLE
Cloud it be build for android?

### ISSUE THREAD

**Issue by wx69wx** [TigerVNC/tigervnc#1710]
**Is your feature request related to a problem? Please describe.**

I have seen it's vncviewer could support audio，it is exciting!  so I want to build it in my android phone. I have install gcc，cmake，fltk…  in termux.  when execute comand below:

cmake vncviewer
make

it give error :
/data/data/com.termux/files/home/vnc/tigervnc-1.13.1/vncviewer/menukey.cxx:30:10: fatal error: 'rfb/keysymdef.h' file not found

How to build it?  thanks a lot!

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by CendioOssman** [comment]
I'm afraid we do not have any audio support in TigerVNC, nor support for Android. Neither of them are likely to show up anytime soon, as I don't think anyone is working on either feature.

The error you are getting is because you need to run just `cmake`, not `cmake vncviewer`. That might get you to compile things, but you won't be able to run things, as TigerVNC is currently only designed for a "normal" Linux system.
