### ISSUE TITLE
Use xwayland sources

### ISSUE THREAD

**Issue by joantolo** [TigerVNC/tigervnc#1728]
At the [xserver](https://gitlab.freedesktop.org/xorg/xserver) project, currently, the `xorg-server` branch is at 21.1.11 version while the `xwayland` one is at 23.2.4 version.
It looks like the xorg-server won't be updated as much as xwayland. 

Maybe it could help to add a `xwayland.patch` and use a `meson.build` file to allow building Xvnc with the newer xwayland sources.

**Comment by CendioOssman** [comment]
I don't think that would be a good idea. I would suspect the xwayland branch doesn't care if they break other X servers, since it is not supposed to be generic.

The master branch still gets updates, so it's not like it is completely dead.

Switching to meson is probably needed either way, though, as even the master branch has dropped autotools.
