### ISSUE TITLE
build error on master

### ISSUE THREAD

**Issue by frinnst** [TigerVNC/tigervnc#177]
[ 87%] Building CXX object vncviewer/CMakeFiles/vncviewer.dir/DesktopWindow.cxx.o
/tmp/tigervnc/vncviewer/DesktopWindow.cxx: In member function 'void DesktopWindow::fullscreen_on()':
/tmp/tigervnc/vncviewer/DesktopWindow.cxx:437:38: error: 'fullscreen_screens' was not declared in this scope
     fullscreen_screens(-1, -1, -1, -1);
                                      ^
/tmp/tigervnc/vncviewer/DesktopWindow.cxx:472:48: error: 'fullscreen_screens' was not declared in this scope
     fullscreen_screens(top, bottom, left, right);
                                                ^
vncviewer/CMakeFiles/vncviewer.dir/build.make:100: recipe for target 'vncviewer/CMakeFiles/vncviewer.dir/DesktopWindow.cxx.o' failed
make[2]: *** [vncviewer/CMakeFiles/vncviewer.dir/DesktopWindow.cxx.o] Error 1
CMakeFiles/Makefile2:775: recipe for target 'vncviewer/CMakeFiles/vncviewer.dir/all' failed
make[1]: *** [vncviewer/CMakeFiles/vncviewer.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

gcc 4.8.4

**Comment by CendioOssman** [comment]
Are you using FLTK 1.3.3? Sounds like you're trying to build against an older version.

**Comment by frinnst** [comment]
Indeed I was! Works just fine with 1.3.3. Sorry for jumping the gun and not investigating myself :-)

**Comment by wyatt8740** [comment]
It's worth mentioning that Debian Jessie is currently using a version of FLTK too old for this to build.

**Comment by bphinz** [comment]
Unfortunately, that's true of virtually all the major enterprise or LTS distributions.  For our official binaries, we have to build and statically link Fltk in because the system supplied version is too old.  Eventually we'll just be able to rely on the distro version, but at least now that Pierre's patches have been accepted into Fltk's code base we don't have to maintain our own custom patches as well.
