### ISSUE TITLE
Option to use `syslog` rather than `%s/.vnc/%s%s.log`

### ISSUE THREAD

**Issue by jcpunk** [TigerVNC/tigervnc#1795]
**Is your feature request related to a problem? Please describe.**
When the VNC server crashes, it is often critical to quickly restart the service.  This leads to the vnc session log being truncated and the messages often showing the cause being lost.

**Describe the solution you'd like**
In addition to the user's ~/.vnc/hostname:display.log, a flag to also direct the messages to syslog.

Perhaps `-D` from vncsession could be extended to this behavior?

**Describe alternatives you've considered**
I've looked at some local wrappers, but they are all a bit hacky.

**Additional context**
[Where logs get truncated](https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/vncsession.c#L456)

**Comment by CendioOssman** [comment]
We try to follow the behaviour of a local login, and I'm not too keen on straying from that principle. User sessions are not normally logged to syslog, which can be very confusing for users.

For your use case, it might be more interesting to explore what modern display managers do, which is to log to the users journal. It is more persistent than a single session, which should solve your issue.

**Comment by CendioOssman** [comment]
#1145 might be an alternative as well.

**Comment by casantos** [comment]
I suppose the service @jcpunk refers to is the systemd one. In this case, the `-D` option does no suffice, since vncsession still closes the std{in,out,err} fd's and redirects all output to the log file, in `run_script()`. Also it would be necessary to send the `xinit` output to syslog, e.g. by piping it to `logger`.

Also is there are multiple VNC services configured on the system all their messages will be mixed in the system log. It would be necessary to pass per-service tag to use when sending the messages to syslog, to prevent confusions.

**Comment by jcpunk** [comment]
I think I've got that in place for https://github.com/TigerVNC/tigervnc/pull/1799
