### ISSUE TITLE
The TLS connection was non-properly terminated

### ISSUE THREAD

**Issue by james7x1** [TigerVNC/tigervnc#1822]
**Describe the bug**
When the network connection between the server and client is disrupted without a physical port interaction (cable being unplugged), I get the following error, "An unexpected error occurred when communicating with the server: readTLS: The TLS connection was non-properly terminated (-110)."
The same error appears when trying to connect to the server device from even different client devices via tigerVNC once the initial error is tripped.
However, the server is still accessible to all devices by using a different client software such as RealVNC or TurboVNC. The only solution I have found is to restart the VNC server.

**To Reproduce**
1. Start a vncserver session on server.
2. Open a tigerVNC Viewer session on the client.
3. Disconnect the router from internet connection (simulate outage or unplug WAN, issue does not appear if computer registers its physical port disconnected)
4. A typical disconnection error appears
5. Reconnect router and attempt to connect to the server again, which causes the error to appear in tigerVNC Viewer.

**Expected behavior**
Expected that the session would close at disconnect and then after connection is restored, the client should be able to access the session again once tigerVNC viewer restarts.

**Client (please complete the following information):**
 - OS: Windows 11
 - VNC client: TigerVNC
 - VNC client version: 1.14.0
 - Client downloaded from: Sourceforge

**Server (please complete the following information):**
 - OS: Ubuntu 22.04 LTS or Fedora xx.x
 - VNC server: turboVNC
 - VNC server version: 3.0.3
 - Server downloaded from: https://github.com/TurboVNC/turbovnc/releases
 - Server was started using: vncserver

**Comment by CendioOssman** [comment]
It's very unexpected that any issue should persist after reconnecting. Could you share some logs from the client and server?

Instructions for getting client logs are available here:

https://github.com/TigerVNC/tigervnc/wiki/Debug-Logs#client-1

**Comment by james7x1** [comment]
@CendioOssman Here are the log files. I was able to kill WiFi on my NIC and get the same result. I just don't get the error if I unplug ethernet from the client or host.

[Client Disconnect.log](https://github.com/user-attachments/files/16730889/Client.Disconnect.log)
[Client TLS Error.log](https://github.com/user-attachments/files/16730890/Client.TLS.Error.log)
[server.log](https://github.com/user-attachments/files/16730891/server.log)

**Comment by CendioOssman** [comment]
Thank you!

The log files show that we get a more expected error for the initial disconnect:

>  TLSInStream: Failure reading TLS data: read: An existing connection was
>               forcibly closed by the remote host. (10054)

On the second connections, we can see that the connection is unexpectedly dropped right after everything is authenticated and initialized.

Looking at the server log, we can see why:

> 23/08/2024 10:39:23 -dontdisconnect: Not shared & existing client
> 23/08/2024 10:39:23   refusing new client 127.0.0.1

The client is configured to not share the session, and the server is configured to refuse the new client in this scenario. It has likely not detected that the previous connection is dead yet.

I'm afraid that I don't see a bug here. You'll need to either reconfigure the client to share connections, or the server to prefer the new client over the old one. I would guess that your other clients have not had their configuration changed to exclusive access, which is why they can connect.
