### ISSUE TITLE
Display not refreshed if no mouse movement

### ISSUE THREAD

**Issue by kiko5931** [TigerVNC/tigervnc#1835]
I have a visual app running on Unix displaying on Windows through the TigerVNC client.
As long as I move my mouse, the display is refreshed otherwise it is freezed.

For instance I have a clock with seconds in the tof left corner of my app.
If I move my mouse, I can see seconds updated.
If I don't do anything with the mouse, seconds are not updated.

Same thing if I get out of the TigerVNC client window, the display is not refreshed.
In previous versions that was working fine (unable to say which older version)

For sure it prevents me from falling asleep ...

Version of the client :
![image](https://github.com/user-attachments/assets/a7c8e67c-f2c1-4760-a8e9-d46ffaad685b)

No screenshot to provide as it is a display refresh issue.
Thanks for help !

**Client:**
 - OS: Windows 11 (also in 10)
 - VNC client: TigerVNC
 - VNC client version: 1.11.0
 - Client downloaded from: RedHat ?? customized by local IT

**Server:**
 - OS: [e.g. Windows 8.1]
 - VNC server: TigerVNC
 - VNC server version: 1.11.0
 - Server downloaded from: RedHat ?? customized by local IT
 - Server was started using: /usr/bin/x0vncserver

**Comment by CendioOssman** [comment]
Historically, I'm afraid these issues have generally been network problems where something is buffering and delaying network traffic.

Do you have any special network setup between the client and server? E.g. a VPN, or other tunnel?

**Comment by joeg1484** [comment]
We are also experiencing this using RHEL 8 client/server... 

Client connected with vncviewer and over time, the connection seems to stop updating the screen unless you move the mouse over the viewer screen. The setup is kiosk mode with Gnome and view only.

Client/Server on RHEL 8 - version 1.12.0-6. We are still on RHEL 8.6 due to the nature of our work - government and a classified environment.

We are using it on a local lan, so just a couple switches on a 40g fiber network. We see traffic passing between the systems using tcpdump, but when the system stops updating, all traffic stops - until you move the mouse over the viewer, then it kicks back up with traffic.

We are tunneling though SSH... starting the client with vncviewer -via user@server :0 (Or :1) 

Server started with x0vncserver -display :1 −AcceptSetDesktopSize=0 −AcceptPointerEvents=0 −AcceptKeyEvents=0 −AlwaysShared −FrameRate=30 −CompareFB=1

Strange thing is that we enabled xdamage and I can see that its enabled, but when we start the vncviewer, it specifically says its falling back to polling because it didnt detect the DAMAGE extension. 

Maybe this is the issue? Is there a way to force DAMAGE with x0vncviewer.

I would be more than happy to start a new ticket for this - I dont mean to hijack the current OP thread, just though it might be relevant to both of us.

**Comment by joeg1484** [comment]
So I did some research on this issue we are having and it does look like packet loss is present as well as tcp re-transmits.

Could someone from VNC explain - or point me to a document - where this would/could cause the screen to freeze until activity is resumed in the viewing window?

Thanks!

**Comment by kiko5931** [comment]
The output on the terminal when I run the vncviewer:
`VNC_USER Geometry:    Desktop geometry is set to 1920x1200+0+0
 XDesktop:    Using evdev codemap
 XDesktop:
NAME=sys XDesktop:    XTest extension present - version 2.2
 XDesktop:    DAMAGE extension not present
 XDesktop:    Will have to poll screen for changes
 XDesktop:    RANDR extension not present
 XDesktop:    Will not be able to handle session resize
tem; ex Main:        failed to bind socket: Address already in use (98)
export DISPLAY=$oldisp;vncviewer localhost &
[1] 1951
[2] - Done (1)             \x0vncserver SecurityTypes=None
system@cmatcwp11li:~/PcvCurrent/CONFM_EXE_RUNTIME/log $
TigerVNC Viewer 64-bit v1.11.0
Built on: 2021-09-10 21:53
Copyright (C) 1999-2020 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.

Thu Sep 26 14:09:52 2024
 DecodeManager: Detected 2 CPU core(s)
 DecodeManager: Creating 2 decoder thread(s)
 CConn:       Connected to host localhost port 5900
 CConnection: Server supports RFB protocol version 3.8
 CConnection: Using RFB protocol version 3.8
 CConnection: Choosing security type VncAuth(2)
 CConn:       Using pixel format depth 24 (32bpp) little-endian rgb888
 CConnection: Enabling continuous updates

Thu Sep 26 14:09:53 2024
 CConn:       SetDesktopSize failed: 1
`

**Comment by CendioOssman** [comment]
> Thanks Cendio for your quick reply. I'm accessing to the vnc server through an ssh connection with MobaXTerm. No specific VPN or else.

MobaXTerm could be the issue in that case. Would you mind seeing if it makes a difference if you use the OpenSSH included in Windows?

Your client and server are also both somewhat old. It would be good if you could test the current version of TigerVNC.

**Comment by kiko5931** [comment]
Thanks very much. Couldn't find out OpenSSH in Windows, I guess our company's ITs got rid of it ... where do you find it?
I'll try to update the viewer also once I get access to our yum repo.

**Comment by fxzxmicah** [comment]
Don't say remote, my vnc server is located in localhost. The interface will also be refreshed with delay.

**Comment by CendioOssman** [comment]
> Thanks very much. Couldn't find out OpenSSH in Windows, I guess our company's ITs got rid of it ... where do you find it?

I don't think there are official downloads, since it's supposed to be included with the system. Some beta releases seem to exist here:

https://github.com/PowerShell/Win32-OpenSSH/releases

**Comment by CendioOssman** [comment]
No response. Closing.
