### ISSUE TITLE
win11 realvnc client can't copy non ascii char to linux tigervnc server

### ISSUE THREAD

**Issue by askgh** [TigerVNC/tigervnc#1843]
I understand that the reason for this issue is that the RealVNC client is not using UTF-8 encoding. It's treating the binary data in the clipboard as ISO-8859 data and encoding it as UTF.

So it's just an encoding error, but the information hasn't been lost. Therefore, for TigerVNC, would it be possible to have an option to decode the data sent by RealVNC?

This way, the RealVNC client could copy and paste Chinese text with the TigerVNC server.

**Comment by CendioOssman** [comment]
The information is unfortunately lost, as you can't deterministically tell if data is UTF-8 or ISO 8859-1. At best, you can guess. Which I'm not sure we want to get in to, given that the protocol is very clear that the data is ISO 8859-1 and nothing else.

Have you talked to RealVNC about this? Ideally, they add support for a better clipboard system. Or share documentation to any existing system they already have so that TigerVNC can add support for it.

**Comment by askgh** [comment]
Here's the English translation:

I'm also currently consulting with RealVNC about this issue.

On the other hand, in my environment, only the RealVNC client connects to TigerVNC. Is there an option where I can force the received clip data to be treated as ISO 8859-1? 

This is because I've checked my server's TigerVNC, and the received data is encoded in ISO 8859-1.

This way, I can start testing on my server first. 
it will not affect other server's tigervnc

**Comment by CendioOssman** [comment]
TigerVNC always expects the data to be ISO 8859-1, so there are no settings for it there. I'm afraid I don't know which settings RealVNC has.

Is there a reason you cannot use the TigerVNC client?

**Comment by askgh** [comment]
The TigerVNC Windows client will actively modify the resolution of the server side.

**Comment by CendioOssman** [comment]
That is something we consider a useful feature, so I'm interested to hear what issues you see with that?

**Comment by askgh** [comment]
Because my VNC server's resolution needs to be fixed at a specific value to accommodate a software inside, 

the Tiger Viewer client changed my resolution, so the app in vncserver cannot work.

**Comment by askgh** [comment]
Because I use the RealVNC client to connect to the TigerVNC server, 
when transferring clipboard content, even though no encoding method is specified, but the encoding method of RealVNC is fixed. 

Therefore, I hope there can be a way in TigerVNC, such as an environment variable or parameter, to specify the clipboard encoding format, so that I can copy Chinese text.

this is important in my work env

**Comment by CendioOssman** [comment]
I'm afraid that I don't think there is any way to get support for Chinese characters between RealVNC and TigerVNC. And there isn't really anything we can do from our end, given that RealVNC is proprietary and undocumented.

RealVNC will need to either document their clipboard extensions, or implement support for the one that TigerVNC supports.

Since there isn't anything we can do here, I'm going to close this issue for now. If you get a response from RealVNC that we can act on, then please comment and we'll open the issue again.
