### ISSUE TITLE
TigerVNC and persistent sessions

### ISSUE THREAD

**Issue by peverett07** [TigerVNC/tigervnc#220]
I need to be able to have persistent sessions enabled in TigerVNCbut I also need it to prompt for a login/pswd eveytime the remote connection is restarted. Any ideas?

**Comment by bphinz** [comment]
On Wed, Oct 14, 2015 at 12:49 PM, peverett07 <notifications@github.com>
wrote:

> I need to be able to have persistent sessions enabled in TigerVNCbut I
> also need it to prompt for a login/pswd eveytime the remote connection is
> restarted. Any ideas?
>
Take a look at the -SecurityTypes option.  The *Plain (Plain, TLSPlain,
x509plain) can be combined with PAM to require the user to authenticate
using the native system facilities rather than just the user's vnc password.

-brian

**Comment by graysky2** [comment]
https://www.mail-archive.com/tigervnc-users@lists.sourceforge.net/msg00321.html
