### ISSUE TITLE
Ubuntu (and Debian?) /etc/default/vncserver is ignored by init.d script

### ISSUE THREAD

**Issue by qnxor** [TigerVNC/tigervnc#261]
The init.d script is actually ignoring the `VNCSERVERARGS[2]` variable that is set in `/etc/default/vncserver`

```
su ${display##*:} -c "cd ~${display##*:} && vncserver :${display%%:*}"
```

Easy fix by

```
su ${display##*:} -c "cd ~${display##*:} && vncserver :${display%%:*}" ${VNCSERVERARGS[2]}
```

A more minor issue is that the init.d script doesn't start if no `.vnc/passwd` file is present, but that shouldn't be a strict condition if vncserver is started with `-localhost --SecurityTypes=None` (typical when using an ssh tunnel).
##

**Comment by CendioOssman** [comment]
@bphinz, it doesn't seem like $VNCSERVERARGS is used anywhere in the Ubuntu packaging.

**Comment by bphinz** [comment]
I just committed 9b9a38c, which fixes the issue with VNCSERVERARGS being ignored.  New binaries are available for testing on the nightly builds page.  I don't see any easy way to made the script smarter about whether or not the passwd file check should actually be enforced though.

**Comment by qnxor** [comment]
On the passwd issue, the following solution works fine (tested). Change the line
```
if [ -e ".vnc/passwd" ]; then
```
to
```
shopt -s nocasematch
if [[ -e .vnc/passwd || ${VNCSERVERARGS[2]} =~ securitytypes=[,a-z0-9]*none ]]; then
```
It also checks if `none` or `*none` is set in the `SecurityTypes` parameter (take note of the case insensitive match enabled by previous `shopt` line. If you want to make it future proof, replace `[,a-z0-9]` with `[^[:space:]]`, just in case you decide to add some security type that is not `[a-z0-9]`

**Comment by qnxor** [comment]
Also added `plain` to my fix above (neither `none` nor `plain` (or their tls/x509 variants) require ~/.vnc/passwd

**Comment by qnxor** [comment]
Actually, if there is no ~/.vnc/passwd file then vncserver prempts you to create one, which doesn't work on a headless machine or if nobody is present at boot. A workaround would be to touch it if `none|plain` is set in the security types, i.e.
```
shopt -s nocasematch
if [[ -e .vnc/passwd || ${VNCSERVERARGS[2]} =~ securitytypes=[,a-z0-9]*(none|plain) ]]; then
    touch .vnc/passwd
```

**Comment by bphinz** [comment]
Yeah, I've been trying to find an appropriate regex but so far no luck.  Your suggestion is clever, but doesn't cover all cases (ie: TLSPlain,TLSvnc).  I haven't been able to get a negative pattern match like "!(vncauth|(x509|tls)vnc)" to work.

**Comment by qnxor** [comment]
Yes it does ... look closer

**Comment by bphinz** [comment]
bphinz@buildhost-trusty-x64:~$ echo $VNCUSERARGS
-geometry 800x600 -nolisten tcp -localhost -SecurityTypes=TLSPlain,TLSvnc
bphinz@buildhost-trusty-x64:~$ if [[ $VNCUSERARGS =~ securitytypes=[,a-z0-9]*(none|plain) ]]; then echo OK; fi
OK

IMO, it shouldn't succeed just because *none or *plain is specified.  It should fail if any of the VncAuth flavors are used and the password file doesn't exist, so I think it has to be a negative match on *vnc*.  Plus, VeNCrypt is also a valid security type...  I didn't try negating the result of the expression though.  Let me do some testing with it.

**Comment by bphinz** [comment]
Damn markdown…  Didn't mean for that to be italicized

**Comment by qnxor** [comment]
I disagree.

First, according to docs, all valid security types are (quoted from `Xvnc --help`): `None, VncAuth, Plain, TLSNone, TLSVnc, TLSPlain, X509None, X509Vnc, X509Plain`

Second, if I set `securitytype=vnc,tlsplain` then I do *not* need a .vnc/passwd file becsause I can login with `tlsplain`. Here `vnc` is accepted, but not required, i.e. the vnc server should start without a passwd file in this case!

This is why you want a positive match on `*none` or `*plain` (and whatever other type is not a derivative of `vnc`).

The positive regex I gave you first matches anything that includes the strings `none` and `plain` ... this includes stuff like `tlsnone`, `tlsplain` or `vnc,tlsnone,x509plain` <-- note the commas and (the existence of `vnc` should not prevent the server from starting if a .vnc/passwd doesn't exist, because `tlsnone` and `x509plain` don't need it).

**Comment by bphinz** [comment]
It's not technically invalid though, as you pointed out, and it's not a security risk so I'm not opposed to issuing a warning and allowing the server to continue.  I'll submit a pull request for something along those lines tonight but I'd like for Pierre to weigh in as well, since I think it makes sense to sync up the behavior across all the supported distros.

**Comment by CendioOssman** [comment]
If you've explicitly specified VNCAuth, then I think we should refuse to proceed if it doesn't work.

Even despite that, we should not be looking for `none` or `plain`. What happens when we add a new authentication? Whatever the goal is it needs to be triggering on the presence of `vnc` in some form.

Regex might not be the best choice here. Set `IFS` to `,` and let the shell split the string. Then you can just loop over it and see if you find anything useful.

**Comment by qnxor** [comment]
Like I said, I can understand that point of view. I don't quite agree with the IFS+iterating approach (it defeats your own argument about adding authentications in the future). I'd just use a negative match on `*vnc`. This is a minor issue in my view, I'm sure any solution you choose will be just fine.

**Comment by qnxor** [comment]
I just installed the .deb for 1.7.1 on an Ubuntu 16.04.1 and adding `-SecurityTypes None` in /etc/default/servers is ignored ... always asks for a password. My /etc/default/vncservers is

```
VNCSERVERS="11001:mylogin"
VNCSERVERARGS[2]="-geometry 1600x900 -nolisten tcp -localhost -SecurityTypes None"
```

I was hoping that this issue I opened a long time ago would be imeplemented. I can provide a fix, but not sure if you guys are interested.

**Comment by qnxor** [comment]
Argh, ignore that. I missed the `VNCSERVERARGS[2]` which should read `VNCSERVERARGS[11001]`.

It may be worth adding a clear explanation in the file comments, i.e. that the display number `$N` must be the array index for `VNCSERVERARGS[$N]`

**Comment by CendioOssman** [comment]
vncserver is now started in a different manner, so closing this issue.
