### ISSUE TITLE
Documentation for ~/.vnc/default.tigervnc

### ISSUE THREAD

**Issue by winny-** [TigerVNC/tigervnc#270]
Is there documentation somewhere about `~/.vnc/default.tigervnc`?

**Comment by CendioOssman** [comment]
Afraid not. The format isn't terribly complex though. It's just the marker string `TigerVNC Configuration file Version 1.0` followed by simple `<setting>=<value>` pairs. The available settings are the one you get from `vncviewer --help` and which are also documented on [the man page](http://tigervnc.org/doc/vncviewer.html).

**Comment by winny-** [comment]
Ah, I didn't have the magic string. Thanks for the clarification. :+1:

**Comment by Corax26** [comment]
@CendioOssman just spent 15 min trying to figure out the expected format for this, the magic string is needed indeed! Could you at least add two lines in `man vncviewer` mentioning this? I have only found a mention of this magic string on this thread...

**Comment by shivanimmagadda** [comment]
In a day i connect to multiple server through tigervnc viewer... i wanted to see if there is way i can create a shortcut so that i can just doubleclick on it to open a tigerviewer.. with out entering userName and passwd again n again... Any help??   also can some one attach the default.tigervnc file ??

**Comment by shivanimmagadda** [comment]
@Corax26 @CendioOssman could you please sample  default.tigervnc file which u guys have.
