### ISSUE TITLE
If user uses java 1.8.0_77 version problem.

### ISSUE THREAD

**Issue by sapientpe** [TigerVNC/tigervnc#289]
Hi,
        When user launches the tigervnc with web-browser.
then it show an error message.
Your security settings have blocked and application form running with and out-of date .
we are using Ubuntu os .can you please help us.

**Comment by bphinz** [comment]
Are both the server and client running Ubuntu, and did you get the packages from us?  IIRC, I never figured out how to sign the applet while building a debian package, so I suspect that's the problem.  Can you try downloading the standalone [VncViewer.jar](http://tigervnc.bphinz.com/nightly/viewers/VncViewer.jar) file and pointing the server to that instead of the one packaged with the .deb and let me know if it works?
-brian

**Comment by sapientpe** [comment]
Thanks brain for your support.
On client side we are using Ubuntu and java version as java version "1.8.0_77"
On server side we are using centos. then is show error message as:
Your security settings have blocked and application form running with and out-of date .
and applet is not loading.
In client machine Ubuntu if we are using java version "1.6.0_31" then 
It is working fine.can you please check it.

**Comment by bphinz** [comment]
What version of both CentOS and TigerVNC are you using on the server side?  Java 6 would not complain because the restrictions on RIAs were not introduced until Java 7u51.

**Comment by bphinz** [comment]
Closing due to lack of information.
