### ISSUE TITLE
VNC Viewer on Windows 10 displays a lot of black

### ISSUE THREAD

**Issue by TheFiZi** [TigerVNC/tigervnc#353]
Just upgraded my CentOS 6 box to TigerVNC 1.7 and restarted my VNC server.

Upgraded TigerVNC on my Windows 10 machine and then attempted to connect to my CentOS server. This is what I see:
![untitled](https://cloud.githubusercontent.com/assets/1762426/18420209/f8c06fd2-7821-11e6-8ea5-f92e5220e011.png)

Closing/re-opening the session does not help. Changing the size of the VNC window on the Windows side does not help (I have automatic resizing enabled).

Downgrading my TigerVNC on my Windows 10 machine to 1.6 works around the issue while my sever continues running 1.7.

**Comment by bphinz** [comment]
Thanks for reporting this.  It's a build issue of some sort.  I upgraded the MXE build environment used to create the windows binaries a couple of weeks ago and this went unnoticed.  I've re-published 1.7.0 binaries built using the previous build environment.  I've tested those on Windows 7 and they looked fine.  On Windows 10, I saw a cosmetic problem that I believe is unrelated and fixed in a post-1.7.0 commit from last week.  Can you please test the newly posted binaries and confirm?  Thanks.

**Comment by TheFiZi** [comment]
That fixed it.
