### ISSUE TITLE
Alternatives to the browser's java plugin should be considered

### ISSUE THREAD

**Issue by Metuchen** [TigerVNC/tigervnc#412]
With the future of browser plugins in doubt (cite: https://www.fxsitecompat.com/en-CA/docs/2016/plug-in-support-has-been-dropped-other-than-flash/), it is clear we should no longer rely upon the browser's Java plugin to deliver the "client-less" VNC experience.  It seems to me, the easiest and most obvious solution would be to switch to javaws as the folks at TurboVNC have done and as recommended by Oracle (cite: https://blogs.oracle.com/java-platform-group/entry/moving_to_a_plugin_free).

**Comment by bphinz** [comment]
Agreed.  I've never really liked applet mode anyway...  It's difficult to support because plugin behavior is inconsistent between OS/browser combinations.  I've always used JWS for deployment in my production environment.

I have some spare cycles coming up and will look into porting over DRC's implementation

**Comment by kingio** [comment]
Maybe http://novnc.com (https://github.com/novnc/noVNC) ?

**Comment by CendioOssman** [comment]
A browser-based client is out of scope of this project, and noVNC fills that role very well. So closing this request.
