### ISSUE TITLE
I just installed Tiger. No error messages ! But ...

### ISSUE THREAD

**Issue by Adgreen** [TigerVNC/tigervnc#422]
I just installed Tiger. No error messages !
But ...
Where are the Help files/ Manuals ?
I have also pressed F1 when opened Config VNC Server and Config Service etc etc ...

**Comment by hildred** [comment]
I'm guessing that you are using windows as the unix builds use traditional man pages for example https://github.com/TigerVNC/tigervnc/blob/master/vncviewer/vncviewer.man or http://tigervnc.org/doc/vncviewer.html is the man page for the viewer (which should be the same on all platforms asside from the path seperator) You can also poke around the other manpages (html versions are at http://tigervnc.org/ ) as an effort has been made to maintain consistent behavior across platform as much as possible.

**Comment by Adgreen** [comment]
Would you like me to start writing a "How to get started" - Once i understand this ... 

Many Thanks !!

But is there nor "How to get started"    Step by step. 

For instance I have installed Tiger Server on my VPS, WinServer 2016. 
Then .. 
One of the first thin I should do ? To register the server / services ?
Register a server. Because I think one needs to do that...

I Click on the Icon in start field "Register VNC Service" "C:\Program Files\TigerVNC\winvnc4.exe" -register
But nothing, nothing happens !!!

Would you like me to start writing a "How to get started" - Once i understand this ... 

Or is there a Step by step - "How to get started"

**Comment by Adgreen** [comment]
I guess there are some things I should Create. 

A server, and name it, and then configure it ?

Create. A Client / viewer  and name it, and then configure it ?

But how do I do that, 

 Step by step - "How to get started" ...

**Comment by Adgreen** [comment]
And yes ...  I have read all these ... 
The man pages for the different programs are available here in HTML form:
vncconfig
vncpasswd
vncserver
vncviewer
x0vncserver
Xvnc

But it does not give me a : Step by step - "How to get started" ...

**Comment by hildred** [comment]
Writing a step by step how to get started is very difficult in that there is a large number of different ways to use vnc even the basic two step instructions of start server, connect to it with viewer does not apply in all cases. Let's start with some simple questions what machines do you want to connect from and to (yes you need more than one computer to use vnc (especially with windows, although with virtual machines this can be confused) in most cases) their ip addresses, can the computers ping each other (most discussion is involved in this one), are they on a trusted network or is some form of cryptography going to be used (tls is easy when it works, but may not because of inconsistent support across vnc products, ssh is more portable but confuses new users on a regular basis), which user session is going to be remote controlled, is it already running, what credentials need to be required for site or regulatory policies to be met (will the account have access to credit card information, patient records, etc.)?

After answering these questions running tiger vnc is actually the easy part. For example if you are in a closed lab with a local non internet ethernet with a dhcp server and two windows boxes, all that is needed is to set a password on the server and register service and either reboot the server or start the service (as long as fast user switching is not giving you fits today) and then connect using a viewer on the other machine. if you are not on a private network crypto is strongly recommended as bare vnc is easy to key sniff and the vncpassword authentication sucks.

Unfortunately there are known issues with recent versions of windows and the winvnc server specifically Microsoft keeps "improving" windows and breaking winvnc, and many of us don't care as tigervnc was forked in an effort to fix unix support. For example to get me to use a windows machine you either have to offer a lot of money or be family. 

If you want to contribute any documentation, It will be welcomed with open arms.

**Comment by Kdmeizk** [comment]
(sorry for this coming, my question is a little related I think, I will delete this message if necessary)
@hildred I just would like to know how I can check if the connection uses TLS (with anonymous mode, not with X.509). The only way I found to check this is when I see protocol "TLS" with Wireshark. But with TigerVNC, I see only TCP and VNC protocol. I unchecked X.509 for viewer and server for these tests.

**Comment by CendioOssman** [comment]
VNC uses an upgrade mechanism for TLS so wireshark will not be able to detect it (until someone improves their dissector at least).

What you can do is check the logs, or open the context menu on the client and check the "Security method" line.

**Comment by Adgreen** [comment]
OK - I´´m learning ....

And I believe i´ll take all this into my sugestion for the Wiki enrty.

A general, portal, Q : 


This open architecture provides considerable flexibility, allowing the use of SSH for a variety of purposes beyond a secure shell. The functionality of the transport layer alone is comparable to Transport Layer Security (TLS); the user-authentication layer is highly extensible with custom authentication methods; and the connection layer provides the ability to multiplex many secondary sessions into a single SSH connection, a feature comparable to BEEP and not available in TLS.
