### ISSUE TITLE
Ubuntu 16 (Xenial Xerius) package?

### ISSUE THREAD

**Issue by patrickmmartin** [TigerVNC/tigervnc#462]
see 

http://c-nergy.be/blog/?p=9962

where they supply their own build.

Given the problems that the default desktop sharing seems to have in Ubuntu currently, this would be much appreciated.

I can test the package, if needed.

**Comment by bphinz** [comment]
We've been supplying Xenial debs since 1.7.0.  You can pick them manually from bintray:

https://dl.bintray.com/tigervnc/stable/ubuntu-16.04LTS/

With 1.8.0 I tried to setup a PPA on bintray but wasn't able to make it work.  Because we only use the free tier, we aren't eligible for support...  Hopefully I can get it figured out before the next release.

**Comment by willsALMANJ** [comment]
The links on bintray are a little messed up. On https://dl.bintray.com/tigervnc/stable/ubuntu-16.04LTS/, the `amd64` link goes to https://dl.bintray.com/tigervnc/stable/ubuntu-16.04LTS/:amd64/ instead of https://dl.bintray.com/tigervnc/stable/ubuntu-16.04LTS/amd64/ (note the extra `:` before `amd64`). It took me a while to figure this out.

By the way, perhaps you could consider attaching the various builds to the release entries on https://github.com/TigerVNC/tigervnc/releases if you wanted something a little more official looking.

**Comment by CendioOssman** [comment]
> The links on bintray are a little messed up. On https://dl.bintray.com/tigervnc/stable/ubuntu-16.04LTS/, the amd64 link goes to https://dl.bintray.com/tigervnc/stable/ubuntu-16.04LTS/:amd64/ instead of https://dl.bintray.com/tigervnc/stable/ubuntu-16.04LTS/amd64/ (note the extra : before amd64). It took me a while to figure this out.

Seems to be a redirect in place as that still works fine for me.

> By the way, perhaps you could consider attaching the various builds to the release entries on https://github.com/TigerVNC/tigervnc/releases if you wanted something a little more official looking.

There's simply too many files for that. Bintray has much better folder view.

**Comment by willsALMANJ** [comment]
Ah, sorry, I didn't realize I had javascript disabled -- the redirect works for me with javascript enabled.

I hadn't realized how many files there are. Maybe the bintray site could be linked to from tigervnc.org or the readme or wiki here.
