### ISSUE TITLE
Java client doesn't ask to accept self-signed certificate

### ISSUE THREAD

**Issue by michalsrb** [TigerVNC/tigervnc#467]
I am using Xvnc server with a X509* security type and a self signed certificate generated using following command:

    openssl req -new -x509 -extensions usr_cert -key $TLSKEY -out $TLSCERT -days 7305 -subj "/CN=$CN/"

When connecting with the native vncviewer, it asks me whether I want to accept it and remember.

However, the java client does not ask me. Instead it shows error message: "java.lang.RuntimeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors"

I checked and the `com.tigervnc.rfb.CSecurityTLS` class would show the confirmation dialog if the exception was `CertPathBuilderException`, but for whatever reason it was `CertPathValidatorException`. Even after reading the java documentation I don't understand what is the practical difference between those two.

Would it be a correct fix to show the confirmation dialog for `CertPathValidatorException`  too?

**Comment by bphinz** [comment]
You're probably right.  What's annoying is that checkServerTrusted() in X509TrustManager is supposed to throw a CertificateException, and neither CertPathValidatorException or CertPathBuilderException are subclasses of that.

**Comment by bphinz** [comment]
The "-extensions usr_cert" argument causes the generated cert to have a CA:false attribute added to the X509v3 Basic Constraints section, hence the CertPathValidatorException rather than CertPathBuilderException.  However, I don't think that any self-signed cert is technically PKIX compliant so if we're going to accept them then I think it makes more sense to add a check that specifically looks for self-signed certs and breaks that case out from other situations where an otherwise valid PKIX compliant path cannot be built (eg: signed certificate issued by a CA not in the default JRE system trust).  It's a pretty straightforward change, I'll try to get something committed tonight.

**Comment by bphinz** [comment]
After doing more homework, I think that accepting this certificate is not the right thing to do.  From what I've read, Firefox and most other browsers would refuse to accept this cert (I'm not sure why OpenSSL would even generate a certificate of this nature).  The fact that the native viewer accepts it is probably what should really be filed as a bug.  If you create a CA cert (without the usr_cert extension) and then use that to sign an end user cert, it should work as expected.

**Comment by michalsrb** [comment]
Thank you for your answers.

Creating one-time CA for it seems like a bit of overkill. I have tried creating self-signed certificate without the usr_cert extension, but it has the same problem. By the way both Firefox and Chrome warn that the certificate is self-signed and require confirmation, but then they work with it.

However, I have investigated it further and found the core issue: It happens only if I previously accepted a different certificate with the same subject.

For example I have two servers, each with automatically generated certificate with subject "CN=Automatic VNC certificate". If I connect to the first one, java client will ask me if I want to accept it. If I do, it will save it in `~/.vnc/x509_savedcerts.pem` and connect successfully. If I attempt to connect to the second server, the java client will give me the `CertPathValidatorException` error.

If I do the same thing with the native client, it will ask me both times and if I accept both times, both certificates will be saved in the `~/.vnc/x509_savedcerts.pem` file. Interestingly, if I use the java client after that, it will connect to both servers without asking.

PS: It also seems that the java client can not add any certificates to `~/.vnc/x509_savedcerts.pem` if any are there already there.

**Comment by bphinz** [comment]
> However, I have investigated it further and found the core issue: It happens only if I previously 
> accepted a different certificate with the same subject.

Ah, good catch.  It looks like I'm using the certificate DN as the key to a collection while iterating over the saved certs.  I'll have to change that to use the thumbprint or something unique instead.

> If I do the same thing with the native client, it will ask me both times and if I accept both times, 
> both certificates will be saved in the ~/.vnc/x509_savedcerts.pem file. Interestingly, if I use the 
> java client after that, it will connect to both servers without asking.

That's by design, if a cert is already in the saved certs file then verification is bypassed.

> PS: It also seems that the java client can not add any certificates to ~/.vnc/x509_savedcerts.pem
> if any are there already there.

That should not be the case, I'll have to look into that.

**Comment by bphinz** [comment]
Would you mind testing 7fcc8614e1ff8c19fd3a1a275fa5ab6eda28f6bd and confirming that it resolves the issue?

**Comment by michalsrb** [comment]
Unfortunately it doesn't resolve the issue. I still get the "java.lang.RuntimeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors".
It seems that even that the certificates are stored in the KeyStore with unique aliases, something else down the way is confused when trying to verify the certificate.

**Comment by bphinz** [comment]
I see what's going on now, and why it works for the native viewer (it explicitly permits certs that fail verification with the status code GNUTLS_CERT_SIGNER_NOT_CA).  I also think that we're not using the ~/.vnc/x509_savedcerts.pem file the way it's meant to be used (in either client).  What I'm going to do is to parse out the certs in the savedcerts file and compute the thumbprint for each one.  If it matches the session host then certificate verification will be bypassed, otherwise it will proceed with prompting the user to accept & store the server cert.  This way, self-signed certs can be supported regardless of whether or not the usr_cert attribute is present.

**Comment by bphinz** [comment]
Can you test 79314c2?  That should resolve both the CertPathValidatorException and also the issue with saving certs when there are already some present.

**Comment by michalsrb** [comment]
Yes! It works now! Thank you for you help.

**Comment by bphinz** [comment]
Great.  I'll merge this in tonight.  Thanks for doing so much leg work to help flush out the underlying issue.

**Comment by bphinz** [comment]
Fixed in 3a7d3c8
