### ISSUE TITLE
Unwanted 2x scaling on Windows Native viewer

### ISSUE THREAD

**Issue by gregorlarson** [TigerVNC/tigervnc#509]
Using a 13-inch ThnkPad with 1920x1080 display, running windoz 7, the native client always appeared 'zoomed in'. This happens with versions 1.7.1 and 1.8.

This zoom-in appears to happen when the remote VNC server resolution is 1920x1080, smaller or larger. I tried various settings but could not prevent this zoom-in behaviour. I tried viewing the same servers (tiger vncserver, or tigervnc scraping server) with the realvnc viewer and the zoom-in is not forced with that viewer (i.e. the entire remote screen can be seen).

**Comment by CendioOssman** [comment]
The scaling is done by Windows, not by us, which is why your changes have little effect. We have #369 for more advanced handling, but until then you'll have to fiddle with the settings in Windows. Scaling can be disabled per application from the compatibility tab if you open properties on the TigerVNC shortcut.
