### ISSUE TITLE
After connecting host clipboard isnt working anymore

### ISSUE THREAD

**Issue by mavarazo** [TigerVNC/tigervnc#520]
Hello,

After connecting to the client (CentOS) the clipboard entirely stops working on the host (Win10). 
When I close the viewer, everything goes back to normal. 

Anyone else detected this behavior? Does anybody know a workaround?

Thanks alot.

**Comment by CendioOssman** [comment]
I'm afraid I'm slightly confused by your wording here.

Are you running WinVNC on the Windows 10 machine, and vncviewer on CentOS?

Are both 1.8.0?

**Comment by mavarazo** [comment]
Sorry... didnt want to confuse...

Im using vncviewer on Win10 to connect to CentOS

**Comment by CendioOssman** [comment]
How are you starting the server on CentOS? And which versions are you using?

**Comment by mavarazo** [comment]
Using: tigervnc-server-1.8.0-1.e17.x86_64
Start: vncserver
Xstartup: 
`
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
exec /etc/X11/xinit/xinitrc
vncconfig -nowin &
`

**Comment by CendioOssman** [comment]
And you are using tigervnc 1.8.0 on the client as well?

Does it help to disable the clipboard in the viewer settings?

**Comment by Pascal666** [comment]
Same problem.  vncviewer64-1.6.0 on Windows 7.  Windows unable to add data to clipboard after Yum upgraded CentOS to 7.4 which included tigervnc-server-1.8.0-1.el7.x86_64.

Workaround:
`yum downgrade http://vault.centos.org/7.3.1611/os/x86_64/Packages/tigervnc-license-1.3.1-9.el7.noarch.rpm http://vault.centos.org/7.3.1611/os/x86_64/Packages/tigervnc-server-1.3.1-9.el7.x86_64.rpm http://vault.centos.org/7.3.1611/os/x86_64/Packages/tigervnc-server-minimal-1.3.1-9.el7.x86_64.rpm`
add `exclude=tigervnc*` to [base] section of /etc/yum.repos.d/CentOS-Base.repo to prevent the broken version from being automatically reinstalled.

**Comment by mavarazo** [comment]
@CendioOssman : Yes, i tried vncviewer64_1.7.1 and vncviewer64_1.8.0

@Pascal666 : Thanks for your workaround, will try it right now

**Comment by CendioOssman** [comment]
I'm afraid I'm unable to reproduce this issue with the RHEL 7 machine I have here. I tried both Windows 7 and Windows 10 as clients.

Are you running the standard Gnome classic desktop?

Do you have any other software installed on your clients that might mess with the clipboard? E.g. Microsoft Office has been known to do so in the past.

**Comment by mavarazo** [comment]
On CentOS I'm forced to use KDE. 
On Windows 10 I've installed Microsoft Office because its the office workstation.

**Comment by CendioOssman** [comment]
I switched to KDE here and still no issues.

Could you try turning off any Office stuff running locally just to see if that is indeed the issue? You may need to hunt for background stuff as well.

**Comment by Pascal666** [comment]
I too am running KDE.  I have Office 2003 installed but was able to reproduce the problem even without it running.  The problem does not occur until you add something to the clipboard on Linux.

I use PuTTY on Windows.  Normally I can highlight text and then click elsewhere in the window to copy it.  Normally if I highlight text in a PuTTY window, then switch to a different window and add something to the clipboard, the highlight will go away.  When this problem is occurring, as soon as I release the mouse from highlighting text the highlight goes away.  It acts like Linux is constantly overwriting the Windows clipboard.

I was able to reproduce this on a new CentOS 7.4 install:
Complete a minimal install
Create a user
yum install tigervnc-server kde-workspace
change the username twice in /usr/lib/systemd/system/vncserver@.service
systemctl enable vncserver@:0
create /home/<user>/.vnc/passwd
mkdir -p /home/<user>/.local/share
chown <user>:<user> -R /home/<user>/.local
reboot

**Comment by bphinz** [comment]
Check to see if klipper is running in the background.  It's notorious for interfering with VNC clipboard transfers.

**Comment by Pascal666** [comment]
@bphinz Yes, KDE on CentOS 7 includes Klipper.  It did not change from 7.3 to 7.4.  Exiting Klipper does appear to be another workaround.

I tested tigervnc-server 1.7.1 from https://dl.bintray.com/tigervnc/stable/el7/RPMS/x86_64/ and it does not have this problem.  1.8.0 from there does.  The release notes for 1.8.0 state "vncconfig no longer needed for clipboard with Xvnc/libvnc.so".  Perhaps something in that change is causing this problem?

**Comment by CendioOssman** [comment]
> @bphinz Yes, KDE on CentOS 7 includes Klipper. It did not change from 7.3 to 7.4. Exiting Klipper does appear to be another workaround.

I'm afraid there's not much we can do then. TigerVNC and Klipper both try to do the same thing, which ends up in the scenario you're seeing. So you need to reconfigure something:

 a) Disable clipboard in TigerVNC
 b) Disable Klipper
 c) Disable PRIMARY sync in TigerVNC
 d) Disable PRIMARY sync in Klipper

> I tested tigervnc-server 1.7.1 from https://dl.bintray.com/tigervnc/stable/el7/RPMS/x86_64/ and it does not have this problem. 1.8.0 from there does. The release notes for 1.8.0 state "vncconfig no longer needed for clipboard with Xvnc/libvnc.so". Perhaps something in that change is causing this problem?

I would wager that you didn't have working clipboard in the previous version for some reason. So essentially you were using option a).

**Comment by Pascal666** [comment]
Clipboard synch works perfectly in 1.3.1 and 1.7.1 with both vncconfig and Klipper running.  Both host and remote can add to and pull from the shared clipboard.  As you suggested, I tried disabling clipboard synch in the TigerVNC client with a 1.8.0 server and the clipboard still did not work correctly.

I can find no configuration options on Klipper for synchronizing the clipboard to another computer.  There is only one config option that uses the word synchronize and it is for an unrelated feature:

Synchronize contents of the clipboard and the selection
Sets the clipboard mode. When an area of the screen is selected with mouse or keyboard, this is called the ?selection?. If this option is selected, the selection and the clipboard is kept the same, so that anything in the selection is immediately available for pasting elsewhere using any method, including the traditional middle mouse button. Otherwise, the selection is recorded in the clipboard history, but the selection can only be pasted using the middle mouse button. Also see the Ignore selection option. See the section called ?Clipboard/Selection Behavior?.

Per Wikipedia: Klipper is a clipboard manager for the KDE interface. It allows users of Unix-like operating systems running the KDE desktop environment to access a history of X Selections, any item of which can be reselected for pasting. It can also be used to react automatically if a certain text is selected (e.g. opening an URL in a browser).

Perhaps there are two different programs named Klipper and you are referring to a different one?

Now that CentOS 7.4 includes 1.8.0 this problem is going to affect more and more people.  If you do not have a server you can test this on, I would be happy to give you remote access to a CentOS 7.4 box.

If you cannot find and fix the clipboard bug that was introduced in 1.8.0, please at least back out the clipboard changes in 1.8.0.  Yes, it was a bit annoying to have to run vncconfig, but it was easy to hide and at least it worked.

Thank you.

**Comment by MarkMielke** [comment]
Klipper has the following obnoxious option that I suspect is causing you difficulty:

> Prevent empty clipboard
> 
> If selected, the clipboard will never be empty: Klipper will insert the most recent item from the clipboard history into the clipboard instead of allowing it to be empty.
> 

See:

https://docs.kde.org/trunk5/en/kde-workspace/klipper/preferences.html

When we upgraded our users to TigerVNC 1.8.0, a small number of users found that cut + paste on their client host broke. I was able to reproduce by enabling this flag, and I was able to clear the problem for users by globally disabling this flag for all deployments by default.

You say that "Clipboard synch works perfectly in 1.3.1 and 1.7.1 with both vncconfig and Klipper running." I think this is not true. It is only that it worked in a reasonable way for you that met your expectations. There were known deficiencies that affected you and others, but this may not have bothered you. Once the deficiencies were addressed with TigerVNC 1.8.0, and now that Klipper is able to "properly" detect the client host clipboard and it is now able to repeatedly override it, you are blaming TigerVNC. But, actually, you should be blaming Klipper. TigerVNC 1.8.0 is just enabling Klipper to be as badly behaved as it was designed to be.

See if turning this obnoxious Klipper flag off resolves your issue. It did for us.

**Comment by Pascal666** [comment]
Thank you @MarkMielke !!  Turning off that option appears to allow the clipboard to work correctly with 1.8.0 with all of Klipper's other features intact.  So the question becomes, why is the new clipboard behavior in 1.8.0 being detected by Klipper as an empty clipboard?

When the same workaround was suggested for Eclipse, Esben Mose Hansen, Klipper sort-of-maintainer, said in [Sept 2009](https://techtavern.wordpress.com/2008/08/10/fixing-copy-paste-issues-on-eclipse-and-kde/#comment-116):
> It is most probably because Eclipse is one of the programs that empties the clipboard before claiming it. If that is case, the best solution would be for Eclipse to stop doing that… at best, it is unnecessary chatter via. the X protocol. It might also introduce a race condition, especially in these multicore days, as you probably see with Klipper here.

**Comment by CendioOssman** [comment]
Yes, thank you for that extra bit of information. I had a look at why Klipper considers the clipboard empty, and I was able to provide a workaround.

This is a general bug in Qt where it sends an incorrect timestamp when requesting the clipboard. A normal X server ignores this, but our code was more strict. So I removed that check in dfc2001b3f681cbd1377a3096781182727f13d24 in order to be more compatible.

**Comment by HanLee13** [comment]
I encountered the same problem and the solution of @MarkMielke does work! Thanks a lot for solving this big problem!

**Comment by shloim** [comment]
@MarkMielke thanks for the klipper tip! This has been a frustrating journey!
I've isolated the klipper setting that causes it, so there's no need to disable it, just:
Right-click the **klipper** icon (Scissors)
Select **Configure Klipper**
Uncheck **[  ] Prevent empty clipboard**
And klipper is no longer a problem!

**Comment by WallStProg** [comment]
Not sure why this was closed -- this is an ongoing problem with CentOS/RH 7 (in my case 7.6.1810).

The problem has nothing to do with KDE, nor Klipper, neither of which I use.  (I use Gnome classic desktop).

FWIW, the workaround suggested by @Pascal666 at https://github.com/TigerVNC/tigervnc/issues/520#issuecomment-334301245 does appear to fix the problem for me, even with multiple vnc client sessions.  So something changed between 1.3 and 1.8 which causes these clipboard problems.

**Comment by codecivet** [comment]
I'm using TigerVNC 1.9.0 for both host and client and had this same issue. None of the suggested solutions worked. I tried completely disabling Klipper and that also did not work.

The workaround for me was using Konsole instead of GNOME terminal. Copy/paste is now working correctly for me.
