### ISSUE TITLE
Error: TigerVnc  install for Centos

### ISSUE THREAD

**Issue by heguangpeng** [TigerVNC/tigervnc#541]
hello ,please help:
Sun Nov 19 21:58:25 2017
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5901
 vncext:      created VNC server for screen 0
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":1"
      after 0 requests (0 known processed) with 0 events remaining.

** (gnome-session-check-accelerated:6170): WARNING **: Could not open X display

(gnome-session-check-accelerated:6170): Gtk-WARNING **: cannot open display: :1

** (gnome-session-check-accelerated:6180): WARNING **: Could not open X display

(gnome-session-check-accelerated:6180): Gtk-WARNING **: cannot open display: :1

** (process:6046): WARNING **: software acceleration check failed: Child process exited with code 1

**Comment by CendioOssman** [comment]
How are you starting the VNC server? Could you include all output and log contents?

**Comment by cuky23** [comment]
I am seeing issues with el7 centos, that I dont see elsewhere.

running packer in headless mode: centos7 vnc locks up, if i use an xterm its fine.  something relating to tty I bet

**Comment by CendioOssman** [comment]
I'm going to need more details than that. How have you configured your VNC server? And how is it started? Manually? Some service? How is that service configured?

**Comment by cuky23** [comment]
centos7 repo version for me will lock up randomly when using it with packer/qemu.

```
Name        : tigervnc-server
Arch        : x86_64
Version     : 1.8.0
Release     : 1.el7
Size        : 213 k
Repo        : base/7/x86_64
```
This doesnt happen on the older version on ubuntu1604 tightvnc Version: 1.3.10-0ubuntu3

The service is kicked off manually by qemu, sometimes it just locks up. with many backsspaces at once.  Like you want do with you were changing the boot line on a linux install.  This only happens for me when i have a Centos7 Host using qemu/vnc connection to ubuntu16. el6 and el7 guests dont need a lot of backspaces to replace the linux boot line, so are not effected.  

it also may be worth mentioning that when i force the X connection to  real window it doesnt happen, this lockup happens when I send the vnc to localhost:59XX

in packer we can this headless mode.

**Comment by CendioOssman** [comment]
Hang on, this is a different issue than the original one. So please open a new issue for your problem.

@heguangpeng, I still need that information for your issue.

**Comment by cuky23** [comment]
my issue around vnv locking up when  using localhost https://github.com/TigerVNC/tigervnc/issues/544

**Comment by CendioOssman** [comment]
No response. Closing.
