### ISSUE TITLE
How to: local server, encrypted (tech support)

### ISSUE THREAD

**Issue by shentino** [TigerVNC/tigervnc#547]
How do I get an encrypted connection to my X server's :0.0?

I heard there was a libvnc module provided by tigervnc somewhere.

I need to know

* how to set the password
* how to encrypt the connection

I would prefer something simple, perhaps by multiplexing it over an SSH tunnel, but I don't know how to do that

**Comment by CendioOssman** [comment]
The basic steps are putting this file in `/etc/X11/xorg.conf.d`:

https://github.com/TigerVNC/tigervnc/blob/master/contrib/packages/rpm/el7/SOURCES/10-libvnc.conf

and following the steps in that file. This assumes you have a built libvnc.so for your Xorg though. We have some distro packages, but otherwise it is best to poke your distribution for a packaging.

For encryption you should have look at the `SecurityTypes` setting, or use the `-via` parameter for vncviewer to use SSH tunneling.
