### ISSUE TITLE
secure connection how ?

### ISSUE THREAD

**Issue by ercanal** [TigerVNC/tigervnc#555]
I used latest nightly builds both for  server and viewer
Configured server with 
SecurityTypes=TLSPlain

and tried to connect with vncviewer64.exe 
I changed settings at security tab
Only "TLS with anonymous certificates" and "Username and Password (insecure without encryption)" 
options are enabled
But on VNC authentication window there was a "This connection is not secure" warning.

Is this true? I thought I was using TLS encryption.

**Comment by hildred** [comment]
It depends on the security types. Tigervnc supports None, VncAuth, Plain, TLSNone, TLSVnc, TLSPlain, X509None, X509Vnc and X509Plain. There are two ways to split them into three groups of three: by password and by encryption. None of course means no password and ill without additional configuration allow anyone to connect. Plain sends username and password unaltered but is just as secure as telnet. (search for `don't use telnet` for all the problems with that.) the vnc types use vnc's own authentication method.which is a text book example of how not to write an authentication method. the TLS methods all use encryption and protect from eavesdropping but not man in the middle. X509 adds a certificate to the TLS methods and also protect against man in the middle.

The other common method is to use ssh port forwarding.

**Comment by bphinz** [comment]
I'm actually working on some changes to this right now that I hope will clarify this banner message some.  As Ben pointed out, TLS* only encrypts and does not verify that the remote server is who they claim to be.  I'm trying to change the banner so that it will look very similar to the URL bar in most browsers, and provide a little more detail about why the connection should not be considered secure.

**Comment by hildred** [comment]
Anonymous certificates are vulnerable to man in the middle. here is how:

Alice opens a vnc connection to a server run by Bob.

Mallory intercepts the connection and pretends to be a vnc server, but opens another connection to Bob's server.

Bob's server asks for the credentials

Malory passes the requests back and forth between Alice and Bob keping what logs she wants and making what changes she wants, an the simplest change is to use an encrypted channel with Alice and a separate one with Bob.

Since the channels are encrypted Eve who is monitoring the channel is unable to get anything useful, and Alice and Bob both feel secure.

Now let's add signed certificates. Bob generates a certificate pair and asks trent to sign it, since Bob knows Alice trusts Trent.

Now when Mallory opens a connection to Bob, he signs the session key with his certificate.

When Mallory intercepts the connection she can either pass the packets unmodified which prevents her from becoming able to intercept the unencrypted session or she can again split the encryption, but Alice will either get an unsigned connection and the same message as you did or if Malory has a certificate it will show as a connection to whoever malory has a certificate for, but as long as trent remains trustworthy and does not give malory  a signature that says she is bob she cannot impersonate him.

Depending on your network topology you may not care.

**Comment by ercanal** [comment]
I am no expert but  if you are connecting to a ssh server for the first time with no previous record of host key/certificate, you can't differentiate if it is the actual server or the man in the middle??

If you are using username/password for ssh ( of course private/public key authentication is much more secure) authentication, I think the only think missing at tigervnc from ssh is the host key files/server definition is missing and is not visible to the user.

**Comment by zamantech** [comment]
are there guide for more secure like using tls?

**Comment by Anonymous2716** [comment]
This is a very old thread but I wanna know how can I configure ssh on the server side.

**Comment by KZHKMT** [comment]
> This is a very old thread but I wanna know how can I configure ssh on the server side.

You mean SSH tunneling?

**Comment by Anonymous2716** [comment]
@KZHKMT yes vnc through ssh tunnel.

**Comment by KZHKMT** [comment]
> @KZHKMT yes vnc through ssh tunnel.
SSH tunnel: ssh -L 5901:localhost:5901 USER@REMOTE_IP
Note: You can use this option "vncserver -localhost yes" for the vncserver to only receive connect from local host
Connect to machine using vncviewer64-1.13.1.exe: 127.0.0.1:1
