### ISSUE TITLE
Cannot connect to vnc when console not signed in.

### ISSUE THREAD

**Issue by iamybj** [TigerVNC/tigervnc#566]
I use this script 
cat /etc/systemd/system/x0vncserver.service
`[Unit]
Description=Remote desktop service (VNC)
After=syslog.target network.target

[Service]
Type=forking
User=bingjuny
ExecStart=/usr/bin/sh -c '/usr/bin/x0vncserver -display :0 -rfbport 5900 -passwordfile /home/bingjuny/.vnc/passwd -AlwaysShared &'

[Install]
WantedBy=multi-user.targe`

I find if the console not signed in , remote computer cannot connect to the vncserver
And I have to restart the service before remote can connect to .

**Comment by CendioOssman** [comment]
If you are not logged in then the user `bingjuny` will not have access to the local console, so this is expected. There is also no polling waiting for the display server to be reachable, so that service would need to be started after you have logged in or it will just fail.

Unfortunately the login mechanism in Linux is rather complex with multiple screen servers stopping and starting. I'm not aware of anything that can handle this switching, and it is not something we are ready to attempt to handle. :/

**Comment by iamybj** [comment]
x0vncserver, just as the name of itself, should just hook display 0, no matter login or not.
