### ISSUE TITLE
Viewer: adding an option for saving username and password

### ISSUE THREAD

**Issue by Smileline** [TigerVNC/tigervnc#568]
Tiger VNC is a powerful tool. 
I have look for an option for saving the username and password, but it's still no found.
It would be better to add an option for that, so that the user don't need to type them every time when login. If we can create a directly connection shortcut, it is more better.

**Comment by hildred** [comment]
Saving the user name would not be a big deal, but saving the password would be a security issue, not a simple fix. There are lots of ways to do this badly including the method used by vnc auth but only four that might be acceptable: a password management plugin framework, integrate with existing password manager, develop our own password manager, and accept password on stdin.

Since tigervnc is cross platform any solution needs to work for java, linux, windows, and mac at a minimum as these are the architectures that the viewer is released for.

Writing a plugin framework is not easy even if you are only targeting a single architecture. Three is a real challenge, plus java should allow the java client to use native plugins when applicable.

Integrating with a password manager would be a good solution, but which one? It should work on all supported platforms, be well supported, have a compatible licence, and auditable code. And once we find one we get complaints because it is not your favorite (for multiple values of your favorite). An alternate would be to support  multiple password managers either one per architecture or multiple per architecture. Patches welcome.

Writing our own password manager is also an issue in that aside from the scope of the project (and limited resources) and ignoring the fact that we are reinventing the wheel each archecure has different security issues, so not happening but donations are welcome.

Accepting the password on standard input (which does not work on windows or java) is on my to do list but I have not worked on it seriously  for several years. It is only useful in some use cases and assumes a user or integrator that is skilled in scripting (and familiar with the security implications). Patches welcome.

**Comment by Smileline** [comment]
Thanks hildred for explanation. It's reasonable.
Happy New Year !!

**Comment by CendioOssman** [comment]
I agree with @hildred, we do not want to get in to the business of storing passwords. Integration with other things might be possible though, but let's handle those under more specific issues. I'll go ahead and close this one.

**Comment by smprather** [comment]
To anyone else that finds their way here, I am using AutoHotkey to handle this. That way I take on the security responsibility. I have a lot of other "watchers" in this loop, so it was easy to add another one.

```
Loop
{
  IfWinExist, VNC authentication
  {
    WinActivate
    Send, ********{enter}
  }
  Sleep, 800
}
```

**Comment by kwerle** [comment]
It would certainly be nice for tiger to support this feature on OS's that have trivial and good ways to store passwords.  I know macos does.  I suppose windows does.  I'm guessing some flavors of linux do.

https://developer.apple.com/documentation/security/keychain_services/keychain_items/adding_a_password_to_the_keychain

https://docs.microsoft.com/en-us/uwp/api/windows.security.credentials.passwordvault?view=winrt-22000

https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.2/html/how_to_configure_server_security/securely_storing_credentials

**Comment by CendioOssman** [comment]
That would probably be a good, secure way. Could you open a new feature request so we don't get things confused by what was discussed here?
