### ISSUE TITLE
TigerVNC is extremely insecure and should not be used.

### ISSUE THREAD

**Issue by a-raccoon** [TigerVNC/tigervnc#601]
Not documented anywhere in the FAQ; TigerVNC passwords (and likely its authentication methods) are entirely insecure.

- Passwords are limited to 8 characters in length, even if you specify 20.
  - Extra characters are silently ignored and TigerVNC pretends they're useful.
  - Try it!: Enter only the first 8 characters of your password to log in.

- Passwords are stored on the server in DES encrypted (effectively plain text).
  - In Windows: HKEY_LOCAL_MACHINE\SOFTWARE\TigerVNC\WinVNC4\Password

- This weakness has been known for at least 11 years and is readily exploited with common tools.
  - (details) https://www.raymond.cc/blog/crack-or-decrypt-vnc-server-encrypted-password/
  - (download) https://www.raymond.cc/blog/wp-content/plugins/download-monitor/download.php?id=232
  - (download) http://aluigi.org/pwdrec/vncpwd.zip
  - (virustotal) https://www.virustotal.com/#/file/9d773bd8045688eb8fbb0baa0dfe161aef1a1feb1a4a696289b13e99707270c9/detection

Passwords should be stored, at minimum, as a one-way hash that cannot be decrypted. They do not need to be decryptable for any practical purpose.  Anyone can brute force an 8 character password, even without gaining momentary access to the local system.

**Comment by CendioOssman** [comment]
That would be nice, but the protocol unfortunately requires the password to be known to the server so we cannot hash it. So any improvements here would require a protocol extension, and getting that widely deployed among other VNC implementations.

As for warning about the length, we already have #370 for that. So I'm afraid I'll close this as a duplicate, unless you have something more tangible to suggest for changing the authentication.

**Comment by a-raccoon** [comment]
If the security of TigerZNC cannot be improved because it must be backwards compatable with intrinsically insecure ZNC protocols of 20 years ago, then that should be documented on the head of every article on the website in bold red lettering.  I was unable to find any overt or easy to find mentions about the weaknesses mentioned above:  DES, 8 character max, stored insecurely where malware regularly scrape passwords.

Does TigerZNC even thwart high-speed brute force password tries and failure attempts?

Similarly, TigerZNC as a project needs to decide whether it wants to stick to being an obsolete backwards compatible program, or a modern and secure program, in a formal statement and liability waiver.  There is clearly not enough urgency to discourage people from using TigerZNC.  The site requires a statement that implores people to stop using this software, toot sweet.

**Comment by bphinz** [comment]
OK, seriously...  This is an open source project, and as the saying goes
"free as in speech, not beer".  If this subject is of such vital importance
to you then why not jump in and help instead of making snarky comments?

**Comment by a-raccoon** [comment]
My remarks are anything but snarky.  You also mistaken user who submit feedback, bug reports and security advisories as "programmers who need to fix it for themselves or shut up."  This is not the case.

**Comment by shyal** [comment]
Agreed. This is hardly snarky. Not only is this horribly insecure, i can't seem to be able to change the port number.. to make matters worse, it seems some bots are trying to brute force attack the server. Not surprising really considering 8 characters provide little to no data entropy.

**Comment by a-raccoon** [comment]
Issue was Closed last year to bury criticism and awareness.

**Comment by shyal** [comment]
Well, what appears to be even worse is that people are recommending disabling the blacklisting features because they're getting bruteforce attacked:

https://superuser.com/questions/437354/vncserver-too-many-security-failures

Given the glaring vulnerabilities i'm switching to:

https://hub.docker.com/r/consol/ubuntu-xfce-vnc/

I'll need to run an security audit on this too, however simply the ability to control the ports via docker, and the fact it's running in a container brings a lot of security from the get go.

**Comment by a-raccoon** [comment]
Let me know your suggestions for a modern/secure Remote Access Tool (RAT) for Windows that's ideally open source and audited, so I can manage my distant family's computers without having to be burdened for days every time I fly out there.

**Comment by shyal** [comment]
Take a look at teamviewer.

**Comment by jursed** [comment]
@a-raccoon Just tunnel the VNC connection through [SSH](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_overview) and have that handle your auth duties. Then, set up the VNC server to only accept loopback connections.

It's not an equivalent of a proper focus on security of the protocol/implementation, and theoretically, the above method [can be exploited](https://serverfault.com/a/752076). But unless you're sending somebody to space or running a nuclear powerplant through VNC, I'd say does the trick.

**Comment by seperman** [comment]
Well, at least for me, after reading this ticket, I'm not gonna even try TigerVNC or any VNC if the protocol is that bad. It is like using MD5 for hashing your password in 2020. Seriously?
Adios.

**Comment by hildred** [comment]
@seperman et al, the only issue is using vnc style passwords. If you use plain passwords with pam and TLS, you are reasonably secure. TLS deals with the plain text on the wire and pam deals with brute forcing and password storage.

**Comment by a-raccoon** [comment]
> @seperman et al, the only issue is using vnc style passwords. If you use plain passwords with pam and TLS, you are reasonably secure. TLS deals with the plain text on the wire and pam deals with brute forcing and password storage.

Where inside TigerVNC can the user enable TLS and PAM?  You know... for Windows Users.

**Comment by vgrozev** [comment]
In my opinion, the issue was not closed "to bury criticism and awareness", but because it does not make sense to spent precious dev resources and time on something that is not meant to be used in an insecure environment and connection in the first place.
Most likely to fix the issue, there is a need to fix the Windows security in general first, and that is not something that the tigervnc team should be doing. 
On the other hand, if someone needs a remote connection to Windows, the RDP protocol is perfectly capable, and with good performance. It might be more buggy and even more insecure, but Microsoft "mitigated" the problems by just suggesting that it should not be used openly through the internet, so it is strongly suggested to be used over VPN.   
As with the RDP clients, the VNC traffic I believe is also meant to be used only through VPN or ssh tunnels (if leaves the local network)
Unlike RDP and other proprietary protocols though, in this case, the appropriate warnings and tags are clearly provided. 
...
As of the question where to enable TLS on the client, it is under the 'Security tab, clearly outlined and easy to find:

![image](https://user-images.githubusercontent.com/1270587/117200554-9547d580-adb9-11eb-9c71-15019c23e938.png)

**Comment by a-raccoon** [comment]
Or, you know, just make the password harder to brute-force, rather than waxing philosophical over it.

Allow longer passwords.  Prohibit more than 3 failed password attempts in a 1 hour period.  Basic siht.

**Comment by jursed** [comment]
You've chosen to ignore:
* Historic context (VNC compatibility/legacy concerns)
* Feasible external solutions (SSH, VPN, ...)
* Alternative courses of action (fix+PR / forking / switching to alternatives)

...and yet you still pontificate here. There is no surer recipe on being ignored by the maintainers than to do exactly that.

**Comment by a-raccoon** [comment]
![security](https://user-images.githubusercontent.com/1052090/117325567-12bd2580-ae4e-11eb-9ec8-fc624d238e77.png)

**Comment by vgrozev** [comment]
@a-raccoon 
Yes, the "security" section clearly states that using just passwords is insecure without encryption (does not matter how long the password is). If encryption is not used it is insecure no matter what,.. not only for the TigerVnc client but for any traffic, connection, or communication.  
It is also exactly the same as with RDP for example, with the major difference that the RDP clients (to the best of my knowledge) do not state that clearly in most cases.

**Comment by COD3HUNT3R** [comment]
Section 7.2.2 https://datatracker.ietf.org/doc/html/rfc6143#section-7.2.2 mentions you can extend security types

Register a sane security types from IANA. Throw it on Hackernews/Reddit. Make everyone adopt it.
https://www.iana.org/assignments/rfb/rfb.xhtml
