### ISSUE TITLE
TigerVNC partially responsive after long periods of time

### ISSUE THREAD

**Issue by xgiovio** [TigerVNC/tigervnc#618]
Hello, i use centOS 7.4, default repos. Updated to the latest version. SSD, 6 cores cpu, 32 gb ram. The server is not under stress and i have plenty of space on ram and ssd. Services on the machine run for months without problems.

I discovered, and i  can reproduce the same bug on different configurations, that after some weeks or months, when i reconnect to the server, the mouse is partially responsive. I mean, the right click works but not the left click, i can move the windows but non always, i can click on the toolbar menu, click on terminal but the keyboard doesn't work.
I have to restart the service and all goes back to normal.
Should i try a nightly build? Right now i'm using the latest 1.8.0-2.
Any advice? Thanks

**Comment by CendioOssman** [comment]
This sounds like your environment has gotten itself in to some funky state. Usually it's a hung keyboard modifier (e.g. Alt). Unfortunately it's a bit difficult to debug without a working keyboard. :/

I don't think a nightly build will improve things.

How are you starting the server?

**Comment by xgiovio** [comment]
Using systemctl enable vncserver@:1.service
The log it’s clear and if i do systemctl restart it reworks without problem.
The same behaviour on 2 different systems with centos 7.4 and plesk

**Comment by CendioOssman** [comment]
Let's try the following then:

SSH in to the machine once this has happened and run `xev -display :1`. Press a few keys on the keyboard in the VNC viewer and see what `xev` prints. Paste the output here.

**Comment by xgiovio** [comment]
Thanks, i’ll let you know

**Comment by sortel64** [comment]
We had a similar issue using the base CentOS 7.4 (unresponsive after screen lock followed by gnome session crash) that seemed to be fixed with a newer version of 'gdm' -24 I think from the CentOS 7 update repo.  I assume that you are up to date but if not, I suggest you try that.

We currently have another possibly related issue on CentOS 7.4 server/Windows client: after disconnecting over night then reconnecting in the morning, the video is scrambled!  I looks like the old days when you set the resolution of a monitor higher that it could handle.  Only restarting the VNC server fixes it.

**Comment by xgiovio** [comment]
Thanks, i’ll check the updates and i’ll let you know if this works

**Comment by xgiovio** [comment]
just updated all. i'll reopen in case of problems. thanks
