### ISSUE TITLE
Re-add "Print" to keys that can open F8 menu before release of 1.9

### ISSUE THREAD

**Issue by qsimpleq** [TigerVNC/tigervnc#670]
Please, revert this commit 31e75ce2288fb387705e7da9d5ef21d2b17baa64 before release of 1.9. Why Print was removed?

I'm use keyboards which have PrintScreen but no Pause, other keys from list are using in usual work and are not comfortable in action (i'm use tigervnc viewer for my main remote workplace).

**Comment by CendioOssman** [comment]
PrintScreen was removed from the list because it rarely works (most systems grab that key so applications cannot use it) and was mostly just confusing people.

Unfortunately we don't really have any good keys left to add to that list, so I'm afraid you'll have to settle for the one least used in your work flow. :/

Long term we might switch to something involving a few modifiers, but nothing substantial has been done there yet.

**Comment by qsimpleq** [comment]
Thanks for the answer.
