### ISSUE TITLE
XINERAMA doesn't seem to be enabled in Xvnc as part of Centos 6.5

### ISSUE THREAD

**Issue by dgotwisner** [TigerVNC/tigervnc#710]
This is equivalent to a bug that was already closed, but the versions don't match.

"yum list tigervnc" gives 1.1.0-24.e16.

"xdpyinfo" doesn't show XINERAMA.

Running XVNC on a CentOS 6.5 machine.  Trying to run libreoffice from a CentOS 7.4.1708 (Core) release.

Libreoffice barfs with the following:
Xlib:  extension "XINERAMA" missing on display "nfw-devperf-01:1".
/usr/lib64/libreoffice/program/soffice.bin: symbol lookup error: /usr/lib64/libreoffice/program/libvclplug_gtk3lo.so: undefined symbol: gdk_wayland_display_get_type

This is the latest XVnc available from CentOS 6.5 from the CentOS repos.

For various reasons, I must run XVnc from the older system.

**Comment by CendioOssman** [comment]
I'm afraid there isn't much we can do here, for multiple reasons. 1.1.0 is ancient and not supported by us. You'll have to talk to Red Hat about that. Secondly, XINERAMA is included in our builds, so it again seems to be a Red Hat issue.

Lastly, the XINERAMA line looks like a warning. The program is crashing because you have some broken library on your system. The `libvclplug_gtk3lo.so` file does not seem to be correctly installed. But this has nothing to do with TigerVNC, so I'm afraid we cannot help you with that.
