### ISSUE TITLE
Keyboard input not recognized in full screen after disengaging xscreensaver

### ISSUE THREAD

**Issue by nachtgeist** [TigerVNC/tigervnc#715]
* host running tigervnc-viewer: Debian/stretch
* host running vncserver: multiple, lx/win don't seem to make a difference

Steps to reproduce:
* start viewer, connect to a server
* F8 → full screen
* let xscreensaver engage (or execute `DISPLAY=:0 xscreensaver-command -lock` from a local tty not running X)
* after entering the user pw in xscreensaver, mouse input is recognized and transfered to the vncserver, keyboard input however is NOT
  * not even F8
  * running xev on the host running vncserver also does not see any kb input, mouse movement is registered
  * this leaves no other way but to kill the viewer from a different local tty

Let me know if you need more information. Thx
Daniel

**Comment by nachtgeist** [comment]
PS: this happens both with the packaged 1.7.0 in Debian/Stretch and with 1.9.0 from Debian/testing

**Comment by CendioOssman** [comment]
xcreensaver is unfortunately not that well behaved when it keyboard to keyboard handling. It doesn't surprise things get screwed up after it is run. :/

What desktop environment are you running on the client? It sounds like some issue with focus events.

**Comment by nachtgeist** [comment]
The initial report refers to xfce4 4.12 and I just reproduced it with twm → same results.

Using twm and gnome-screensaver instead of xscreensaver makes things even worse. In that case, when g-s activates, not even the password text field receives any kb input.

**Comment by CendioOssman** [comment]
Yeah, twm is probably a worst case scenario since it has very poor support for modern features (such as full screen). But Xfce should work fine.

I think I'll have to test this myself. I would expect xscreensaver to be blocked from messing up our keyboard.

**Comment by MarkMielke** [comment]
One of our users hit the gnome-screensaver lock up described on RHEL 7 with Xfce. This one is really bad for users. I haven't had time to investigate further and noticed this issue which matches what I believe we saw. 

I've hit an issue with xscreensaver when rdesktop having focus where when I unlocked the screen, keyboard didn't register in any window. But if I changed focus to another window keyboard restored. This one I haven't had time to investigate yet but I assumed xscreensaver was at fault.

**Comment by CendioOssman** [comment]
Right, so I tested this here and I can reproduce it with xscreensaver. However both mate-screensaver and gnome-screensaver seem to work just fine.

The bug is that we aren't getting any FocusIn event. We get a nice FocusOut when xscreensaver steals the focus from us, but we never get it back. I'm not sure who to blame here. I'd say the window manager, as that is what's supposed to handle focus. But if this happens to several window managers then perhaps xscreensaver is doing something naughty.

I don't see use being able to do anything here. The system is not giving us focus and it's not a good idea to try and override that. I would recommend you file a bug with the respective window managers and see if they can figure out why we aren't given focus back after the screen saver is done.
