### ISSUE TITLE
Alt-Tab doesn't work (viewer on Mac, server on Linux)

### ISSUE THREAD

**Issue by kflu** [TigerVNC/tigervnc#721]
TigerVNC viewer doesn't work. But Chicken VNC viewer does work. Both using the same vncserver. The expected behavior is that when pressing "option-tab", windows should cycle through.

I used `xev` to dump raw keyboard press. With pressing Option key on Mac, TigerVNC gives me:

```
KeyPress event, serial 36, synthetic NO, window 0x800001,
    root 0x268, subw 0x0, time 357993510, (822,440), root:(824,459),
    state 0x0, keycode 203 (keysym 0xff7e, Mode_switch), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 36, synthetic NO, window 0x800001,
    root 0x268, subw 0x0, time 357993654, (822,440), root:(824,459),
    state 0x0, keycode 203 (keysym 0xff7e, Mode_switch), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

However, when pressing "option key" chicken vnc viewer gives me

```
KeyPress event, serial 36, synthetic NO, window 0x800001,
    root 0x268, subw 0x0, time 357895481, (311,779), root:(313,798),
    state 0x0, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 36, synthetic NO, window 0x800001,
    root 0x268, subw 0x0, time 357895481, (311,779), root:(313,798),
    state 0x1, keycode 64 (keysym 0xffe7, Meta_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 36, synthetic NO, window 0x800001,
    root 0x268, subw 0x0, time 357895481, (311,779), root:(313,798),
    state 0x9, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 36, synthetic NO, window 0x800001,
    root 0x268, subw 0x0, time 357895609, (311,779), root:(313,798),
    state 0x8, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

Is there a way I can tell tigervnc viewer how to map client keys?

**Comment by CendioOssman** [comment]
This is per design (albeit poorly documented). The problem is that Alt on macOS behaves more like AltGr on other systems. So TigerVNC's client changes the meaning of some keys to get things more reliable. We currently have this mapping:

 Left option => Mode shift ("AltGr")
 Right option => ISO level 3 shift (also "AltGr")
 Left Command => Left Alt
 Right Command => Left Windows key

So to get an Alt+Tab on the Linux side you press Cmd+Tab locally. I'm afraid the mapping is not configurable.

You can also try enabling the `RawKeyboard` setting on the server. At that point the layout configured on the client is ignored and it relies fully on what's configured on the server.

Hope this helps.

**Comment by kflu** [comment]
Thanks. Chicken VNC viewer has a feature that allows user to map modifier keys differently. I was also having modifier key issue (windows key not recognized) with Chicken VNC but with that feature I was able to solve it. 

Does tiger vnc viewer has a similar feature?

**Comment by CendioOssman** [comment]
No, I'm afraid we do not have a remapping feature. If you want to use keys grabbed by the OS then the only option currently is to run fullscreen where all keys are sent to the server.

**Comment by maksimt** [comment]
Is there any way to make `-RawKeyboard` more discoverable? I suppose you couldn't make it on by default because of backwards compatibility? Perhaps it could be highlighted in the Input menu on the client?

For context this was super confusing for me, and I got really lucky that I found this github issue. I'm using mac --[TigerVNC Client] --> [TigerVNC Server] --> linux/X11. When I pressed Option_L (i.e. Win_L) on the mac it kept getting interpreted as Mode_Switch in xev. I wanted to map Option_L on mac to Alt_L on linux. At first I tried xmodmap and then xkb. Then I used karabiner to remap keys on the mac. But somehow I couldn't get rid of Mode_Switch on linux. When I would remove it from one keycode it would get re-assigned to a random empty keycode. I think I only decided to look into TigerVNC settings once another VNC client didn't map Option_L to Mode_Switch. Then I found this issue, added `-RawKeyboard`, set a 1-line `xmodmap` and boom 16 hours later I got Option_L mapped to Alt_L...

**Comment by Wren6991** [comment]
> So to get an Alt+Tab on the Linux side you press Cmd+Tab locally. I'm afraid the mapping is not configurable.

This no longer works, at least on MacOS Tahoe. TigerVNC doesn't capture the local Cmd+Tab, so you just switch away from the VNC viewer to a different local window. This is no longer a sane default -- please either change the default or make it configurable.

Would it be reasonable to map Option as Alt instead of AltGr, if and only if the Tab key is also pressed? That would give a reliable way of getting Alt+Tab through to the server (without modifying server config) and I don't think it breaks anything that relies on AltGr.

Sorry to comment on a closed issue, but it seems like new issues on this topic are getting closed as duplicates of this one.

**Comment by CendioOssman** [comment]
If it's a regression, then please test which version of TigerVNC where it stopped working and open a new issue. Keyboard grab was recently changed, but the idea was that the user experience should be the same.

**Comment by Wren6991** [comment]
I tested as far back as 1.11.0 stable (September 2020) and the behaviour is the same, so I think this might be a regression caused by a MacOS change rather than a regression in TigerVNC's keyboard grabbing implementation. I'm on MacOS Tahoe 26.3.1 (a).
