### ISSUE TITLE
Clipboard still not work with unicode

### ISSUE THREAD

**Issue by aiden0z** [TigerVNC/tigervnc#918]
**Describe the bug**

Clipboard still not work with unicode.

**To Reproduce**

1. Using VncViewer-1.10.80.jar connect to vnc server 1.10.80;
2. Display ??? when copy unicode string to the out browser;

**Expected behavior**
Unicode string should display normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/6779243/70978465-c2271a00-20ea-11ea-9cf0-a1cbc1d168c1.png)

**Client (please complete the following information):**
 - OS: MAC OS 10.15.2
 - VNC client: [VncViewer-1.10.80.jar](http://tigervnc.bphinz.com/nightly/viewers/VncViewer-1.10.80.jar)
 - VNC client version: 1.10.80
 - Client downloaded from: http://tigervnc.bphinz.com/nightly/viewers/VncViewer-1.10.80.jar

**Server (please complete the following information):**
 - OS: Ubuntu 16.04.6
 - VNC server: 1.10.80+20191215gitc59f195d-1ubuntu1
 - VNC server version: 1.10.80
 - Server downloaded from: http://tigervnc.bphinz.com/nightly/ubuntu-16.04LTS/amd64/tigervncserver_1.10.80+20191215gitc59f195d-1ubuntu1_amd64.deb
 - Server was started using: tigervncserver

**Additional context**

**Comment by bphinz** [comment]
The java client does not yet support the RFB protocol extensions required for unicode.  It's something that I'm working on but it's very difficult because on Windows the clipboard data is internally presented in a way that frequently causes the JRE to run out of heap memory.  I can't give an ETA as to when this will be implemented, but I just finished refactoring a lot of RFB code specifically so that I could start on this.

**Comment by aiden0z** [comment]
I also test xtigervncviewer 1.10.80 on ubuntu 18.04 with tigervncserver on ubuntu 18.04, the clipboard also still not work with unicode.

**Comment by CendioOssman** [comment]
Is the server also 1.10.80? Could you share a log file with us?

**Comment by aiden0z** [comment]
The clipboard now works with tigervnc 1.10.1 on ubuntu 20.04。
