### ISSUE TITLE
building src rpm in CENTOS6

### ISSUE THREAD

**Issue by redhavoc** [TigerVNC/tigervnc#948]
When trying to build tigervnc 1.10 using the source rpm for rhel6 on centos 6.9, I get the following error

/opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.2/ld: ../../opt/tigervnc/tigervnc16/usr/lib64/libfltk.a(Fl_Window_shape.o): undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
//lib64/libdl.so.2: error adding symbols: DSO missing from command line

I tried building it with devtoolset 3/7/8 and all get the same issue. If I use the standard gcc (4.4.7), it does not understand the -march=westmere option which is added automatically set from the rpmbuild scripts, even if I override it with CFLAGS/CXXFLAGS to core2

Any ideas on what is missing?

**Comment by bphinz** [comment]
I tried to go down the path of using devtoolset as well, since the newest versions of gnutls won't build with the older compiler on el6, but ultimately gave up because it became too complicated and the builds took even longer than the enormous amount of time that they already take.  I will look to see if I can find the spec file that I ended up with for that effort, but IIRC I saw the same thing and had to add a "-ldl" to the linker flags.

**Comment by CendioOssman** [comment]
The underlying issue seems to be that you only have a static version of FLTK and not a dynamic one. This is an issue with devtoolset rather than TigerVNC. You could try the static build option for TigerVNC which tries to work around some of these issues. It's a bit best effort though.

**Comment by redhavoc** [comment]
I actualy solved the issue by setting -ldl on LDFLAGS before issuing the rpmbuild command
export LDFLAGS="-ldl"

Thanks for the help
