### ISSUE TITLE
How to properly config tiger vncserver in order to make the connection is regarded as secure by the viewer?

### ISSUE THREAD

**Issue by desert0616** [TigerVNC/tigervnc#987]
I try to set the config -SecurityTypes=VeNCrypt,TLSVnc but it still shows "This connection is not secure"  when typing the password.

So, how to properly config tiger vncserver in order to make the connection is regarded as secure by the viewer?

Thanks.

**Comment by bphinz** [comment]
The TLS* security types are regarded as insecure because they use Anonymous Diffie-Hellman which provides no assurance against man-in-the-middle attacks.  In order to establish a "secure" connection you should use one of the X509* security types, which use certificates for the encryption (so it's not just a matter of configuring the viewer).

**Comment by bphinz** [comment]
See here for more info: https://github.com/TigerVNC/tigervnc/wiki/Secure-your-connection
